package model.view;

import java.math.BigDecimal;

import java.sql.Date;

import model.entity.XxboqActivityDetailsEOImpl;
import model.entity.XxboqActivityPlanningEOImpl;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 23 10:23:15 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ActivityLevelPlanningVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ActivityId {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getActivityId();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setActivityId((BigDecimal)value);
            }
        },
        ActivityLevelLineid {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getActivityLevelLineid();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setActivityLevelLineid((BigDecimal)value);
            }
        },
        ActivityStructure {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getActivityStructure();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setActivityStructure((String)value);
            }
        },
        BoqQuantity {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getBoqQuantity();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setBoqQuantity((BigDecimal)value);
            }
        },
        BuId {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getBuId();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setBuId((BigDecimal)value);
            }
        },
        CreatedBy {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        },
        CreationDate {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        },
        HeaderId {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getHeaderId();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setHeaderId((BigDecimal)value);
            }
        },
        LastUpdatedBy {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        },
        LastUpdatedDate {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        },
        ProjectId {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getProjectId();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setProjectId((BigDecimal)value);
            }
        },
        StructureId {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getStructureId();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setStructureId((BigDecimal)value);
            }
        },
        Uom {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getUom();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setUom((String)value);
            }
        },
        ActivityId1 {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getActivityId1();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setActivityId1((BigDecimal)value);
            }
        },
        Description {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getDescription();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        },
        ActivityCode {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getActivityCode();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setActivityCode((String)value);
            }
        },
        TransBalQty {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getTransBalQty();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setTransBalQty((BigDecimal)value);
            }
        },
        TransFromMonth {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getTransFromMonth();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setTransFromMonth((String)value);
            }
        },
        TransToMonth {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getTransToMonth();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setTransToMonth((String)value);
            }
        },
        TransFromLineLevelId {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getTransFromLineLevelId();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setTransFromLineLevelId((Long)value);
            }
        },
        TransToLineLevelId {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getTransToLineLevelId();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setTransToLineLevelId((Long)value);
            }
        },
        PlanningScheduleHdrVO {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getPlanningScheduleHdrVO();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        JobLevelPlanningVO {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getJobLevelPlanningVO();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        ActivityLineLevelPlanVO {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getActivityLineLevelPlanVO();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        ActivityLineLevelPlanVO1 {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getActivityLineLevelPlanVO1();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        ActivityLineLevelPlanVO2 {
            public Object get(ActivityLevelPlanningVORowImpl obj) {
                return obj.getActivityLineLevelPlanVO2();
            }

            public void put(ActivityLevelPlanningVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(ActivityLevelPlanningVORowImpl object);

        public abstract void put(ActivityLevelPlanningVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ACTIVITYID = AttributesEnum.ActivityId.index();
    public static final int ACTIVITYLEVELLINEID =
        AttributesEnum.ActivityLevelLineid.index();
    public static final int ACTIVITYSTRUCTURE =
        AttributesEnum.ActivityStructure.index();
    public static final int BOQQUANTITY = AttributesEnum.BoqQuantity.index();
    public static final int BUID = AttributesEnum.BuId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int LASTUPDATEDBY =
        AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE =
        AttributesEnum.LastUpdatedDate.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int STRUCTUREID = AttributesEnum.StructureId.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int ACTIVITYID1 = AttributesEnum.ActivityId1.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int ACTIVITYCODE = AttributesEnum.ActivityCode.index();
    public static final int TRANSBALQTY = AttributesEnum.TransBalQty.index();
    public static final int TRANSFROMMONTH =
        AttributesEnum.TransFromMonth.index();
    public static final int TRANSTOMONTH = AttributesEnum.TransToMonth.index();
    public static final int TRANSFROMLINELEVELID =
        AttributesEnum.TransFromLineLevelId.index();
    public static final int TRANSTOLINELEVELID =
        AttributesEnum.TransToLineLevelId.index();
    public static final int PLANNINGSCHEDULEHDRVO =
        AttributesEnum.PlanningScheduleHdrVO.index();
    public static final int JOBLEVELPLANNINGVO =
        AttributesEnum.JobLevelPlanningVO.index();
    public static final int ACTIVITYLINELEVELPLANVO =
        AttributesEnum.ActivityLineLevelPlanVO.index();
    public static final int ACTIVITYLINELEVELPLANVO1 =
        AttributesEnum.ActivityLineLevelPlanVO1.index();
    public static final int ACTIVITYLINELEVELPLANVO2 =
        AttributesEnum.ActivityLineLevelPlanVO2.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ActivityLevelPlanningVORowImpl() {
    }

    /**
     * Gets XxboqActivityPlanningEO entity object.
     * @return the XxboqActivityPlanningEO
     */
    public XxboqActivityPlanningEOImpl getXxboqActivityPlanningEO() {
        return (XxboqActivityPlanningEOImpl)getEntity(0);
    }

    /**
     * Gets XxboqActivityDetailsEO entity object.
     * @return the XxboqActivityDetailsEO
     */
    public XxboqActivityDetailsEOImpl getXxboqActivityDetailsEO() {
        return (XxboqActivityDetailsEOImpl)getEntity(1);
    }

    /**
     * Gets the attribute value for ACTIVITY_ID using the alias name ActivityId.
     * @return the ACTIVITY_ID
     */
    public BigDecimal getActivityId() {
        return (BigDecimal)getAttributeInternal(ACTIVITYID);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVITY_ID using the alias name ActivityId.
     * @param value value to set the ACTIVITY_ID
     */
    public void setActivityId(BigDecimal value) {
        setAttributeInternal(ACTIVITYID, value);
    }

    /**
     * Gets the attribute value for ACTIVITY_LEVEL_LINEID using the alias name ActivityLevelLineid.
     * @return the ACTIVITY_LEVEL_LINEID
     */
    public BigDecimal getActivityLevelLineid() {
        return (BigDecimal)getAttributeInternal(ACTIVITYLEVELLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVITY_LEVEL_LINEID using the alias name ActivityLevelLineid.
     * @param value value to set the ACTIVITY_LEVEL_LINEID
     */
    public void setActivityLevelLineid(BigDecimal value) {
        setAttributeInternal(ACTIVITYLEVELLINEID, value);
    }

    /**
     * Gets the attribute value for ACTIVITY_STRUCTURE using the alias name ActivityStructure.
     * @return the ACTIVITY_STRUCTURE
     */
    public String getActivityStructure() {
        return (String)getAttributeInternal(ACTIVITYSTRUCTURE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVITY_STRUCTURE using the alias name ActivityStructure.
     * @param value value to set the ACTIVITY_STRUCTURE
     */
    public void setActivityStructure(String value) {
        setAttributeInternal(ACTIVITYSTRUCTURE, value);
    }

    /**
     * Gets the attribute value for BOQ_QUANTITY using the alias name BoqQuantity.
     * @return the BOQ_QUANTITY
     */
    public BigDecimal getBoqQuantity() {
        return (BigDecimal)getAttributeInternal(BOQQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for BOQ_QUANTITY using the alias name BoqQuantity.
     * @param value value to set the BOQ_QUANTITY
     */
    public void setBoqQuantity(BigDecimal value) {
        setAttributeInternal(BOQQUANTITY, value);
    }

    /**
     * Gets the attribute value for BU_ID using the alias name BuId.
     * @return the BU_ID
     */
    public BigDecimal getBuId() {
        return (BigDecimal)getAttributeInternal(BUID);
    }

    /**
     * Sets <code>value</code> as attribute value for BU_ID using the alias name BuId.
     * @param value value to set the BU_ID
     */
    public void setBuId(BigDecimal value) {
        setAttributeInternal(BUID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for HEADER_ID using the alias name HeaderId.
     * @return the HEADER_ID
     */
    public BigDecimal getHeaderId() {
        return (BigDecimal)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_ID using the alias name HeaderId.
     * @param value value to set the HEADER_ID
     */
    public void setHeaderId(BigDecimal value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public BigDecimal getProjectId() {
        return (BigDecimal)getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(BigDecimal value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for STRUCTURE_ID using the alias name StructureId.
     * @return the STRUCTURE_ID
     */
    public BigDecimal getStructureId() {
        return (BigDecimal)getAttributeInternal(STRUCTUREID);
    }

    /**
     * Sets <code>value</code> as attribute value for STRUCTURE_ID using the alias name StructureId.
     * @param value value to set the STRUCTURE_ID
     */
    public void setStructureId(BigDecimal value) {
        setAttributeInternal(STRUCTUREID, value);
    }

    /**
     * Gets the attribute value for UOM using the alias name Uom.
     * @return the UOM
     */
    public String getUom() {
        return (String)getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as attribute value for UOM using the alias name Uom.
     * @param value value to set the UOM
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for ACTIVITY_ID using the alias name ActivityId1.
     * @return the ACTIVITY_ID
     */
    public BigDecimal getActivityId1() {
        return (BigDecimal)getAttributeInternal(ACTIVITYID1);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVITY_ID using the alias name ActivityId1.
     * @param value value to set the ACTIVITY_ID
     */
    public void setActivityId1(BigDecimal value) {
        setAttributeInternal(ACTIVITYID1, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ACTIVITY_CODE using the alias name ActivityCode.
     * @return the ACTIVITY_CODE
     */
    public String getActivityCode() {
        return (String)getAttributeInternal(ACTIVITYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVITY_CODE using the alias name ActivityCode.
     * @param value value to set the ACTIVITY_CODE
     */
    public void setActivityCode(String value) {
        setAttributeInternal(ACTIVITYCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransBalQty.
     * @return the TransBalQty
     */
    public BigDecimal getTransBalQty() {
        if (getBoqQuantity() != null &&
            getActivityLineLevelPlanVO().first() != null) {
            Row[] rows = getActivityLineLevelPlanVO().getAllRowsInRange();
            BigDecimal Quantity = new BigDecimal(0);
            if (rows.length > 0) {
                for (int i = 0; i < rows.length; i++) {
                    if (rows[i].getAttribute("BoqQuantity") != null) {
                        Quantity =
                                Quantity.add(new BigDecimal(rows[i].getAttribute("BoqQuantity").toString()));
                    }
                }
            }
            return getBoqQuantity().subtract(Quantity);
        }
        return (BigDecimal)getAttributeInternal(TRANSBALQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransBalQty.
     * @param value value to set the  TransBalQty
     */
    public void setTransBalQty(BigDecimal value) {
        setAttributeInternal(TRANSBALQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransFromMonth.
     * @return the TransFromMonth
     */
    public String getTransFromMonth() {
        return (String)getAttributeInternal(TRANSFROMMONTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransFromMonth.
     * @param value value to set the  TransFromMonth
     */
    public void setTransFromMonth(String value) {
        setAttributeInternal(TRANSFROMMONTH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransToMonth.
     * @return the TransToMonth
     */
    public String getTransToMonth() {
        return (String)getAttributeInternal(TRANSTOMONTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransToMonth.
     * @param value value to set the  TransToMonth
     */
    public void setTransToMonth(String value) {
        setAttributeInternal(TRANSTOMONTH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransFromLineLevelId.
     * @return the TransFromLineLevelId
     */
    public Long getTransFromLineLevelId() {
        return (Long)getAttributeInternal(TRANSFROMLINELEVELID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransFromLineLevelId.
     * @param value value to set the  TransFromLineLevelId
     */
    public void setTransFromLineLevelId(Long value) {
        setAttributeInternal(TRANSFROMLINELEVELID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransToLineLevelId.
     * @return the TransToLineLevelId
     */
    public Long getTransToLineLevelId() {
        return (Long)getAttributeInternal(TRANSTOLINELEVELID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransToLineLevelId.
     * @param value value to set the  TransToLineLevelId
     */
    public void setTransToLineLevelId(Long value) {
        setAttributeInternal(TRANSTOLINELEVELID, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link PlanningScheduleHdrVO.
     */
    public Row getPlanningScheduleHdrVO() {
        return (Row)getAttributeInternal(PLANNINGSCHEDULEHDRVO);
    }

    /**
     * Sets the master-detail link PlanningScheduleHdrVO between this object and <code>value</code>.
     */
    public void setPlanningScheduleHdrVO(Row value) {
        setAttributeInternal(PLANNINGSCHEDULEHDRVO, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link JobLevelPlanningVO.
     */
    public RowIterator getJobLevelPlanningVO() {
        return (RowIterator)getAttributeInternal(JOBLEVELPLANNINGVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ActivityLineLevelPlanVO.
     */
    public RowIterator getActivityLineLevelPlanVO() {
        return (RowIterator)getAttributeInternal(ACTIVITYLINELEVELPLANVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ActivityLineLevelPlanVO1.
     */
    public RowSet getActivityLineLevelPlanVO1() {
        return (RowSet)getAttributeInternal(ACTIVITYLINELEVELPLANVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ActivityLineLevelPlanVO2.
     */
    public RowSet getActivityLineLevelPlanVO2() {
        return (RowSet)getAttributeInternal(ACTIVITYLINELEVELPLANVO2);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
