package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 23 10:23:15 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ActivityLevelPlanningVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ActivityLevelPlanningVOImpl() {
    }
}
