package model.view;

import java.math.BigDecimal;

import java.sql.Date;

import model.entity.XxUploadErrorsEOImpl;

import model.entity.XxboqValidationCostCodeEOImpl;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 30 13:37:13 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BoqUploadErrorsVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ColumnName {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getColumnName();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setColumnName((String)value);
            }
        },
        CreatedBy {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        },
        CreationDate {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        },
        LastUpdatedBy {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        },
        LastUpdatedDate {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        },
        LineNumber {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getLineNumber();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setLineNumber((BigDecimal)value);
            }
        },
        ReferenceNumber {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getReferenceNumber();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setReferenceNumber((String)value);
            }
        },
        Remarks {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getRemarks();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        },
        RowID {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getRowID();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setRowID((String)value);
            }
        },
        TableCode {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getTableCode();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setTableCode((String)value);
            }
        },
        UploadId {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getUploadId();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setUploadId((BigDecimal)value);
            }
        },
        ValidationLineId {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getValidationLineId();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setValidationLineId((Number)value);
            }
        },
        ValidationHeaderId {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getValidationHeaderId();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setValidationHeaderId((Number)value);
            }
        },
        ValidationLineId1 {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getValidationLineId1();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setValidationLineId1((Number)value);
            }
        },
        ValidationCostCodeId {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getValidationCostCodeId();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setValidationCostCodeId((Number)value);
            }
        },
        ValidationCostCodeId1 {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getValidationCostCodeId1();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setValidationCostCodeId1((Number)value);
            }
        },
        ValidationResourceId {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getValidationResourceId();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setValidationResourceId((Number)value);
            }
        },
        BillDescription {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getBillDescription();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setBillDescription((String)value);
            }
        },
        BillQuantity {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getBillQuantity();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setBillQuantity((String)value);
            }
        },
        BoqLevel {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getBoqLevel();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setBoqLevel((String)value);
            }
        },
        CandyNetFinalAmount {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getCandyNetFinalAmount();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setCandyNetFinalAmount((String)value);
            }
        },
        CandyNetRate {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getCandyNetRate();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setCandyNetRate((String)value);
            }
        },
        FinalQuantity {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getFinalQuantity();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setFinalQuantity((String)value);
            }
        },
        Item {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getItem();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setItem((String)value);
            }
        },
        PageItem {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getPageItem();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setPageItem((String)value);
            }
        },
        PriceCode {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getPriceCode();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setPriceCode((String)value);
            }
        },
        SellingAmount {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getSellingAmount();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setSellingAmount((String)value);
            }
        },
        SellingAmount1 {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getSellingAmount1();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setSellingAmount1((String)value);
            }
        },
        SellingRate {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getSellingRate();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setSellingRate((String)value);
            }
        },
        Trade {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getTrade();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setTrade((String)value);
            }
        },
        Uom {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getUom();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setUom((String)value);
            }
        },
        CostCode {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getCostCode();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setCostCode((String)value);
            }
        },
        CostCodeDescription {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getCostCodeDescription();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setCostCodeDescription((String)value);
            }
        },
        ResourceCode {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getResourceCode();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setResourceCode((String)value);
            }
        },
        FinalRate {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getFinalRate();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setFinalRate((String)value);
            }
        },
        NetUseUnit {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getNetUseUnit();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setNetUseUnit((String)value);
            }
        },
        ResourceDescription {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getResourceDescription();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setResourceDescription((String)value);
            }
        },
        Uom1 {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getUom1();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setUom1((String)value);
            }
        },
        ValidationCostCodeId2 {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getValidationCostCodeId2();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setValidationCostCodeId2((Number)value);
            }
        },
        ValidationResourceId1 {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getValidationResourceId1();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setValidationResourceId1((Number)value);
            }
        },
        ReferenceId {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getReferenceId();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setReferenceId((BigDecimal)value);
            }
        },
        BoqValidationHeaderVO {
            public Object get(BoqUploadErrorsVORowImpl obj) {
                return obj.getBoqValidationHeaderVO();
            }

            public void put(BoqUploadErrorsVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(BoqUploadErrorsVORowImpl object);

        public abstract void put(BoqUploadErrorsVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int COLUMNNAME = AttributesEnum.ColumnName.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY =
        AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE =
        AttributesEnum.LastUpdatedDate.index();
    public static final int LINENUMBER = AttributesEnum.LineNumber.index();
    public static final int REFERENCENUMBER =
        AttributesEnum.ReferenceNumber.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int ROWID = AttributesEnum.RowID.index();
    public static final int TABLECODE = AttributesEnum.TableCode.index();
    public static final int UPLOADID = AttributesEnum.UploadId.index();
    public static final int VALIDATIONLINEID =
        AttributesEnum.ValidationLineId.index();
    public static final int VALIDATIONHEADERID =
        AttributesEnum.ValidationHeaderId.index();
    public static final int VALIDATIONLINEID1 =
        AttributesEnum.ValidationLineId1.index();
    public static final int VALIDATIONCOSTCODEID =
        AttributesEnum.ValidationCostCodeId.index();
    public static final int VALIDATIONCOSTCODEID1 =
        AttributesEnum.ValidationCostCodeId1.index();
    public static final int VALIDATIONRESOURCEID =
        AttributesEnum.ValidationResourceId.index();
    public static final int BILLDESCRIPTION =
        AttributesEnum.BillDescription.index();
    public static final int BILLQUANTITY = AttributesEnum.BillQuantity.index();
    public static final int BOQLEVEL = AttributesEnum.BoqLevel.index();
    public static final int CANDYNETFINALAMOUNT =
        AttributesEnum.CandyNetFinalAmount.index();
    public static final int CANDYNETRATE = AttributesEnum.CandyNetRate.index();
    public static final int FINALQUANTITY =
        AttributesEnum.FinalQuantity.index();
    public static final int ITEM = AttributesEnum.Item.index();
    public static final int PAGEITEM = AttributesEnum.PageItem.index();
    public static final int PRICECODE = AttributesEnum.PriceCode.index();
    public static final int SELLINGAMOUNT =
        AttributesEnum.SellingAmount.index();
    public static final int SELLINGAMOUNT1 =
        AttributesEnum.SellingAmount1.index();
    public static final int SELLINGRATE = AttributesEnum.SellingRate.index();
    public static final int TRADE = AttributesEnum.Trade.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int COSTCODE = AttributesEnum.CostCode.index();
    public static final int COSTCODEDESCRIPTION =
        AttributesEnum.CostCodeDescription.index();
    public static final int RESOURCECODE = AttributesEnum.ResourceCode.index();
    public static final int FINALRATE = AttributesEnum.FinalRate.index();
    public static final int NETUSEUNIT = AttributesEnum.NetUseUnit.index();
    public static final int RESOURCEDESCRIPTION =
        AttributesEnum.ResourceDescription.index();
    public static final int UOM1 = AttributesEnum.Uom1.index();
    public static final int VALIDATIONCOSTCODEID2 =
        AttributesEnum.ValidationCostCodeId2.index();
    public static final int VALIDATIONRESOURCEID1 =
        AttributesEnum.ValidationResourceId1.index();
    public static final int REFERENCEID = AttributesEnum.ReferenceId.index();
    public static final int BOQVALIDATIONHEADERVO =
        AttributesEnum.BoqValidationHeaderVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BoqUploadErrorsVORowImpl() {
    }

    /**
     * Gets XxUploadErrorsEO entity object.
     * @return the XxUploadErrorsEO
     */
    public XxUploadErrorsEOImpl getXxUploadErrorsEO() {
        return (XxUploadErrorsEOImpl)getEntity(0);
    }

    /**
     * Gets XxboqValidationLinesEO entity object.
     * @return the XxboqValidationLinesEO
     */
    public EntityImpl getXxboqValidationLinesEO() {
        return (EntityImpl)getEntity(1);
    }

    /**
     * Gets XxboqValidationCostCodeEO entity object.
     * @return the XxboqValidationCostCodeEO
     */
    public XxboqValidationCostCodeEOImpl getXxboqValidationCostCodeEO() {
        return (XxboqValidationCostCodeEOImpl)getEntity(2);
    }

    /**
     * Gets XxboqValidationResourceEO entity object.
     * @return the XxboqValidationResourceEO
     */
    public EntityImpl getXxboqValidationResourceEO() {
        return (EntityImpl)getEntity(3);
    }

    /**
     * Gets the attribute value for COLUMN_NAME using the alias name ColumnName.
     * @return the COLUMN_NAME
     */
    public String getColumnName() {
        return (String)getAttributeInternal(COLUMNNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COLUMN_NAME using the alias name ColumnName.
     * @param value value to set the COLUMN_NAME
     */
    public void setColumnName(String value) {
        setAttributeInternal(COLUMNNAME, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for LINE_NUMBER using the alias name LineNumber.
     * @return the LINE_NUMBER
     */
    public BigDecimal getLineNumber() {
        return (BigDecimal)getAttributeInternal(LINENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_NUMBER using the alias name LineNumber.
     * @param value value to set the LINE_NUMBER
     */
    public void setLineNumber(BigDecimal value) {
        setAttributeInternal(LINENUMBER, value);
    }

    /**
     * Gets the attribute value for REFERENCE_NUMBER using the alias name ReferenceNumber.
     * @return the REFERENCE_NUMBER
     */
    public String getReferenceNumber() {
        return (String)getAttributeInternal(REFERENCENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for REFERENCE_NUMBER using the alias name ReferenceNumber.
     * @param value value to set the REFERENCE_NUMBER
     */
    public void setReferenceNumber(String value) {
        setAttributeInternal(REFERENCENUMBER, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for ROWID using the alias name RowID.
     * @return the ROWID
     */
    public String getRowID() {
        return (String)getAttributeInternal(ROWID);
    }

    /**
     * Sets <code>value</code> as attribute value for ROWID using the alias name RowID.
     * @param value value to set the ROWID
     */
    public void setRowID(String value) {
        setAttributeInternal(ROWID, value);
    }

    /**
     * Gets the attribute value for TABLE_CODE using the alias name TableCode.
     * @return the TABLE_CODE
     */
    public String getTableCode() {
        return (String)getAttributeInternal(TABLECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TABLE_CODE using the alias name TableCode.
     * @param value value to set the TABLE_CODE
     */
    public void setTableCode(String value) {
        setAttributeInternal(TABLECODE, value);
    }

    /**
     * Gets the attribute value for UPLOAD_ID using the alias name UploadId.
     * @return the UPLOAD_ID
     */
    public BigDecimal getUploadId() {
        return (BigDecimal)getAttributeInternal(UPLOADID);
    }

    /**
     * Sets <code>value</code> as attribute value for UPLOAD_ID using the alias name UploadId.
     * @param value value to set the UPLOAD_ID
     */
    public void setUploadId(BigDecimal value) {
        setAttributeInternal(UPLOADID, value);
    }

    /**
     * Gets the attribute value for VALIDATION_LINE_ID using the alias name ValidationLineId.
     * @return the VALIDATION_LINE_ID
     */
    public Number getValidationLineId() {
        return (Number)getAttributeInternal(VALIDATIONLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for VALIDATION_LINE_ID using the alias name ValidationLineId.
     * @param value value to set the VALIDATION_LINE_ID
     */
    public void setValidationLineId(Number value) {
        setAttributeInternal(VALIDATIONLINEID, value);
    }

    /**
     * Gets the attribute value for VALIDATION_HEADER_ID using the alias name ValidationHeaderId.
     * @return the VALIDATION_HEADER_ID
     */
    public Number getValidationHeaderId() {
        return (Number)getAttributeInternal(VALIDATIONHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for VALIDATION_HEADER_ID using the alias name ValidationHeaderId.
     * @param value value to set the VALIDATION_HEADER_ID
     */
    public void setValidationHeaderId(Number value) {
        setAttributeInternal(VALIDATIONHEADERID, value);
    }

    /**
     * Gets the attribute value for VALIDATION_LINE_ID using the alias name ValidationLineId1.
     * @return the VALIDATION_LINE_ID
     */
    public Number getValidationLineId1() {
        return (Number)getAttributeInternal(VALIDATIONLINEID1);
    }

    /**
     * Sets <code>value</code> as attribute value for VALIDATION_LINE_ID using the alias name ValidationLineId1.
     * @param value value to set the VALIDATION_LINE_ID
     */
    public void setValidationLineId1(Number value) {
        setAttributeInternal(VALIDATIONLINEID1, value);
    }

    /**
     * Gets the attribute value for VALIDATION_COST_CODE_ID using the alias name ValidationCostCodeId.
     * @return the VALIDATION_COST_CODE_ID
     */
    public Number getValidationCostCodeId() {
        return (Number)getAttributeInternal(VALIDATIONCOSTCODEID);
    }

    /**
     * Sets <code>value</code> as attribute value for VALIDATION_COST_CODE_ID using the alias name ValidationCostCodeId.
     * @param value value to set the VALIDATION_COST_CODE_ID
     */
    public void setValidationCostCodeId(Number value) {
        setAttributeInternal(VALIDATIONCOSTCODEID, value);
    }

    /**
     * Gets the attribute value for VALIDATION_COST_CODE_ID using the alias name ValidationCostCodeId1.
     * @return the VALIDATION_COST_CODE_ID
     */
    public Number getValidationCostCodeId1() {
        return (Number)getAttributeInternal(VALIDATIONCOSTCODEID1);
    }

    /**
     * Sets <code>value</code> as attribute value for VALIDATION_COST_CODE_ID using the alias name ValidationCostCodeId1.
     * @param value value to set the VALIDATION_COST_CODE_ID
     */
    public void setValidationCostCodeId1(Number value) {
        setAttributeInternal(VALIDATIONCOSTCODEID1, value);
    }

    /**
     * Gets the attribute value for VALIDATION_RESOURCE_ID using the alias name ValidationResourceId.
     * @return the VALIDATION_RESOURCE_ID
     */
    public Number getValidationResourceId() {
        return (Number)getAttributeInternal(VALIDATIONRESOURCEID);
    }

    /**
     * Sets <code>value</code> as attribute value for VALIDATION_RESOURCE_ID using the alias name ValidationResourceId.
     * @param value value to set the VALIDATION_RESOURCE_ID
     */
    public void setValidationResourceId(Number value) {
        setAttributeInternal(VALIDATIONRESOURCEID, value);
    }

    /**
     * Gets the attribute value for BILL_DESCRIPTION using the alias name BillDescription.
     * @return the BILL_DESCRIPTION
     */
    public String getBillDescription() {
        return (String)getAttributeInternal(BILLDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for BILL_DESCRIPTION using the alias name BillDescription.
     * @param value value to set the BILL_DESCRIPTION
     */
    public void setBillDescription(String value) {
        setAttributeInternal(BILLDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for BILL_QUANTITY using the alias name BillQuantity.
     * @return the BILL_QUANTITY
     */
    public String getBillQuantity() {
        return (String)getAttributeInternal(BILLQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for BILL_QUANTITY using the alias name BillQuantity.
     * @param value value to set the BILL_QUANTITY
     */
    public void setBillQuantity(String value) {
        setAttributeInternal(BILLQUANTITY, value);
    }

    /**
     * Gets the attribute value for BOQ_LEVEL using the alias name BoqLevel.
     * @return the BOQ_LEVEL
     */
    public String getBoqLevel() {
        return (String)getAttributeInternal(BOQLEVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for BOQ_LEVEL using the alias name BoqLevel.
     * @param value value to set the BOQ_LEVEL
     */
    public void setBoqLevel(String value) {
        setAttributeInternal(BOQLEVEL, value);
    }

    /**
     * Gets the attribute value for CANDY_NET_FINAL_AMOUNT using the alias name CandyNetFinalAmount.
     * @return the CANDY_NET_FINAL_AMOUNT
     */
    public String getCandyNetFinalAmount() {
        return (String)getAttributeInternal(CANDYNETFINALAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for CANDY_NET_FINAL_AMOUNT using the alias name CandyNetFinalAmount.
     * @param value value to set the CANDY_NET_FINAL_AMOUNT
     */
    public void setCandyNetFinalAmount(String value) {
        setAttributeInternal(CANDYNETFINALAMOUNT, value);
    }

    /**
     * Gets the attribute value for CANDY_NET_RATE using the alias name CandyNetRate.
     * @return the CANDY_NET_RATE
     */
    public String getCandyNetRate() {
        return (String)getAttributeInternal(CANDYNETRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CANDY_NET_RATE using the alias name CandyNetRate.
     * @param value value to set the CANDY_NET_RATE
     */
    public void setCandyNetRate(String value) {
        setAttributeInternal(CANDYNETRATE, value);
    }

    /**
     * Gets the attribute value for FINAL_QUANTITY using the alias name FinalQuantity.
     * @return the FINAL_QUANTITY
     */
    public String getFinalQuantity() {
        return (String)getAttributeInternal(FINALQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for FINAL_QUANTITY using the alias name FinalQuantity.
     * @param value value to set the FINAL_QUANTITY
     */
    public void setFinalQuantity(String value) {
        setAttributeInternal(FINALQUANTITY, value);
    }

    /**
     * Gets the attribute value for ITEM using the alias name Item.
     * @return the ITEM
     */
    public String getItem() {
        return (String)getAttributeInternal(ITEM);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM using the alias name Item.
     * @param value value to set the ITEM
     */
    public void setItem(String value) {
        setAttributeInternal(ITEM, value);
    }

    /**
     * Gets the attribute value for PAGE_ITEM using the alias name PageItem.
     * @return the PAGE_ITEM
     */
    public String getPageItem() {
        return (String)getAttributeInternal(PAGEITEM);
    }

    /**
     * Sets <code>value</code> as attribute value for PAGE_ITEM using the alias name PageItem.
     * @param value value to set the PAGE_ITEM
     */
    public void setPageItem(String value) {
        setAttributeInternal(PAGEITEM, value);
    }

    /**
     * Gets the attribute value for PRICE_CODE using the alias name PriceCode.
     * @return the PRICE_CODE
     */
    public String getPriceCode() {
        return (String)getAttributeInternal(PRICECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRICE_CODE using the alias name PriceCode.
     * @param value value to set the PRICE_CODE
     */
    public void setPriceCode(String value) {
        setAttributeInternal(PRICECODE, value);
    }

    /**
     * Gets the attribute value for SELLING_AMOUNT using the alias name SellingAmount.
     * @return the SELLING_AMOUNT
     */
    public String getSellingAmount() {
        return (String)getAttributeInternal(SELLINGAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for SELLING_AMOUNT using the alias name SellingAmount.
     * @param value value to set the SELLING_AMOUNT
     */
    public void setSellingAmount(String value) {
        setAttributeInternal(SELLINGAMOUNT, value);
    }

    /**
     * Gets the attribute value for SELLING_AMOUNT using the alias name SellingAmount1.
     * @return the SELLING_AMOUNT
     */
    public String getSellingAmount1() {
        return (String)getAttributeInternal(SELLINGAMOUNT1);
    }

    /**
     * Sets <code>value</code> as attribute value for SELLING_AMOUNT using the alias name SellingAmount1.
     * @param value value to set the SELLING_AMOUNT
     */
    public void setSellingAmount1(String value) {
        setAttributeInternal(SELLINGAMOUNT1, value);
    }

    /**
     * Gets the attribute value for SELLING_RATE using the alias name SellingRate.
     * @return the SELLING_RATE
     */
    public String getSellingRate() {
        return (String)getAttributeInternal(SELLINGRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SELLING_RATE using the alias name SellingRate.
     * @param value value to set the SELLING_RATE
     */
    public void setSellingRate(String value) {
        setAttributeInternal(SELLINGRATE, value);
    }

    /**
     * Gets the attribute value for TRADE using the alias name Trade.
     * @return the TRADE
     */
    public String getTrade() {
        return (String)getAttributeInternal(TRADE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRADE using the alias name Trade.
     * @param value value to set the TRADE
     */
    public void setTrade(String value) {
        setAttributeInternal(TRADE, value);
    }

    /**
     * Gets the attribute value for UOM using the alias name Uom.
     * @return the UOM
     */
    public String getUom() {
        return (String)getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as attribute value for UOM using the alias name Uom.
     * @param value value to set the UOM
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for COST_CODE using the alias name CostCode.
     * @return the COST_CODE
     */
    public String getCostCode() {
        return (String)getAttributeInternal(COSTCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for COST_CODE using the alias name CostCode.
     * @param value value to set the COST_CODE
     */
    public void setCostCode(String value) {
        setAttributeInternal(COSTCODE, value);
    }

    /**
     * Gets the attribute value for COST_CODE_DESCRIPTION using the alias name CostCodeDescription.
     * @return the COST_CODE_DESCRIPTION
     */
    public String getCostCodeDescription() {
        return (String)getAttributeInternal(COSTCODEDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for COST_CODE_DESCRIPTION using the alias name CostCodeDescription.
     * @param value value to set the COST_CODE_DESCRIPTION
     */
    public void setCostCodeDescription(String value) {
        setAttributeInternal(COSTCODEDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for RESOURCE_CODE using the alias name ResourceCode.
     * @return the RESOURCE_CODE
     */
    public String getResourceCode() {
        return (String)getAttributeInternal(RESOURCECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for RESOURCE_CODE using the alias name ResourceCode.
     * @param value value to set the RESOURCE_CODE
     */
    public void setResourceCode(String value) {
        setAttributeInternal(RESOURCECODE, value);
    }


    /**
     * Gets the attribute value for FINAL_RATE using the alias name FinalRate.
     * @return the FINAL_RATE
     */
    public String getFinalRate() {
        return (String)getAttributeInternal(FINALRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for FINAL_RATE using the alias name FinalRate.
     * @param value value to set the FINAL_RATE
     */
    public void setFinalRate(String value) {
        setAttributeInternal(FINALRATE, value);
    }


    /**
     * Gets the attribute value for NET_USE_UNIT using the alias name NetUseUnit.
     * @return the NET_USE_UNIT
     */
    public String getNetUseUnit() {
        return (String)getAttributeInternal(NETUSEUNIT);
    }

    /**
     * Sets <code>value</code> as attribute value for NET_USE_UNIT using the alias name NetUseUnit.
     * @param value value to set the NET_USE_UNIT
     */
    public void setNetUseUnit(String value) {
        setAttributeInternal(NETUSEUNIT, value);
    }

    /**
     * Gets the attribute value for RESOURCE_DESCRIPTION using the alias name ResourceDescription.
     * @return the RESOURCE_DESCRIPTION
     */
    public String getResourceDescription() {
        return (String)getAttributeInternal(RESOURCEDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for RESOURCE_DESCRIPTION using the alias name ResourceDescription.
     * @param value value to set the RESOURCE_DESCRIPTION
     */
    public void setResourceDescription(String value) {
        setAttributeInternal(RESOURCEDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for UOM using the alias name Uom1.
     * @return the UOM
     */
    public String getUom1() {
        return (String)getAttributeInternal(UOM1);
    }

    /**
     * Sets <code>value</code> as attribute value for UOM using the alias name Uom1.
     * @param value value to set the UOM
     */
    public void setUom1(String value) {
        setAttributeInternal(UOM1, value);
    }


    /**
     * Gets the attribute value for VALIDATION_COST_CODE_ID using the alias name ValidationCostCodeId2.
     * @return the VALIDATION_COST_CODE_ID
     */
    public Number getValidationCostCodeId2() {
        return (Number)getAttributeInternal(VALIDATIONCOSTCODEID2);
    }

    /**
     * Sets <code>value</code> as attribute value for VALIDATION_COST_CODE_ID using the alias name ValidationCostCodeId2.
     * @param value value to set the VALIDATION_COST_CODE_ID
     */
    public void setValidationCostCodeId2(Number value) {
        setAttributeInternal(VALIDATIONCOSTCODEID2, value);
    }

    /**
     * Gets the attribute value for VALIDATION_RESOURCE_ID using the alias name ValidationResourceId1.
     * @return the VALIDATION_RESOURCE_ID
     */
    public Number getValidationResourceId1() {
        return (Number)getAttributeInternal(VALIDATIONRESOURCEID1);
    }

    /**
     * Sets <code>value</code> as attribute value for VALIDATION_RESOURCE_ID using the alias name ValidationResourceId1.
     * @param value value to set the VALIDATION_RESOURCE_ID
     */
    public void setValidationResourceId1(Number value) {
        setAttributeInternal(VALIDATIONRESOURCEID1, value);
    }

    /**
     * Gets the attribute value for REFERENCE_ID using the alias name ReferenceId.
     * @return the REFERENCE_ID
     */
    public BigDecimal getReferenceId() {
        return (BigDecimal)getAttributeInternal(REFERENCEID);
    }

    /**
     * Sets <code>value</code> as attribute value for REFERENCE_ID using the alias name ReferenceId.
     * @param value value to set the REFERENCE_ID
     */
    public void setReferenceId(BigDecimal value) {
        setAttributeInternal(REFERENCEID, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link BoqValidationHeaderVO.
     */
    public Row getBoqValidationHeaderVO() {
        return (Row)getAttributeInternal(BOQVALIDATIONHEADERVO);
    }

    /**
     * Sets the master-detail link BoqValidationHeaderVO between this object and <code>value</code>.
     */
    public void setBoqValidationHeaderVO(Row value) {
        setAttributeInternal(BOQVALIDATIONHEADERVO, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
