package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 25 10:19:51 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BOQUploadIntVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BOQUploadIntVOImpl() {
    }
}
