package model.view;

import java.math.BigDecimal;

import java.sql.Date;

import model.applicationmodule.BOQUploadsAMImpl;
import model.applicationmodule.CandyBillofQuantityAMImpl;
import model.applicationmodule.CommonUtilsAMImpl;

import model.entity.XxboqBillOfQtyHdrEOImpl;

import model.masterentity.ContractHeadersEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 13 15:06:13 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CandyBOQSearchVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        BuName {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getBuName();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setBuName((String)value);
            }
        },
        TransCustomerName {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getTransCustomerName();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setTransCustomerName((String)value);
            }
        },
        ApprovedBy {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getApprovedBy();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setApprovedBy((String)value);
            }
        },
        ApprovedDate {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getApprovedDate();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setApprovedDate((Date)value);
            }
        },
        BoqHeaderId {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getBoqHeaderId();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setBoqHeaderId((BigDecimal)value);
            }
        },
        BusinessUnitId {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getBusinessUnitId();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setBusinessUnitId((BigDecimal)value);
            }
        },
        CreatedBy {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        },
        ContractNumber {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getContractNumber();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setContractNumber((String)value);
            }
        },
        Cognomen {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getCognomen();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setCognomen((String)value);
            }
        },
        ProjectName {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getProjectName();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setProjectName((String)value);
            }
        },
        ProjectNumber {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getProjectNumber();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setProjectNumber((String)value);
            }
        },
        TransStatus {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getTransStatus();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setTransStatus((String)value);
            }
        },
        Status {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getStatus();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        },
        Version {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getVersion();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setVersion((BigDecimal)value);
            }
        },
        BudgetType {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getBudgetType();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setBudgetType((String)value);
            }
        },
        TransBudgetType {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getTransBudgetType();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setTransBudgetType((String)value);
            }
        },
        TransBaseLine {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getTransBaseLine();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setTransBaseLine((String)value);
            }
        },
        CreationDate {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        },
        IbcNumber {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getIbcNumber();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setIbcNumber((String)value);
            }
        },
        IbcReason {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getIbcReason();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setIbcReason((String)value);
            }
        },
        ImportDate {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getImportDate();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setImportDate((Date)value);
            }
        },
        LastUpdatedBy {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        },
        LastUpdatedDate {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        },
        ProjectId {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getProjectId();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setProjectId((BigDecimal)value);
            }
        },
        RevisionDate {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getRevisionDate();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setRevisionDate((Date)value);
            }
        },
        BuId {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getBuId();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setBuId((Number)value);
            }
        },
        ProjectId1 {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getProjectId1();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setProjectId1((Number)value);
            }
        },
        TransBudgetCode {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getTransBudgetCode();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setTransBudgetCode((String)value);
            }
        },
        TotalCandyNetFinalAmount {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getTotalCandyNetFinalAmount();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setTotalCandyNetFinalAmount((BigDecimal)value);
            }
        },
        TotalCandyNetFinalAmount1 {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getTotalCandyNetFinalAmount1();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setTotalCandyNetFinalAmount1((BigDecimal)value);
            }
        },
        TransAbsoluteError {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getTransAbsoluteError();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setTransAbsoluteError((BigDecimal)value);
            }
        },
        TransErrorPercentage {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getTransErrorPercentage();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setTransErrorPercentage((BigDecimal)value);
            }
        },
        TotalNetFinalAmount {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getTotalNetFinalAmount();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setTotalNetFinalAmount((BigDecimal)value);
            }
        },
        CurrentFlag {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getCurrentFlag();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setCurrentFlag((String)value);
            }
        },
        TransCandyNetFinalAmountTotal {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getTransCandyNetFinalAmountTotal();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setTransCandyNetFinalAmountTotal((BigDecimal)value);
            }
        },
        TransNetFinalAmountTotal {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getTransNetFinalAmountTotal();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setTransNetFinalAmountTotal((BigDecimal)value);
            }
        },
        BuName1 {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getBuName1();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setBuName1((String)value);
            }
        },
        ProjectNumber1 {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getProjectNumber1();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setProjectNumber1((String)value);
            }
        },
        TransBudgetType1 {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getTransBudgetType1();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setTransBudgetType1((String)value);
            }
        },
        TransPrecision {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getTransPrecision();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setTransPrecision((BigDecimal)value);
            }
        },
        TransCurrentFlag {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getTransCurrentFlag();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setTransCurrentFlag((String)value);
            }
        },
        BaseLine {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getBaseLine();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setBaseLine((String)value);
            }
        },
        TransTotalRevenue {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getTransTotalRevenue();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setTransTotalRevenue((BigDecimal)value);
            }
        },
        TransTotalCostBudget {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getTransTotalCostBudget();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setTransTotalCostBudget((BigDecimal)value);
            }
        },
        TransFileName {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getTransFileName();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setTransFileName((String)value);
            }
        },
        ContractId {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getContractId();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setContractId((BigDecimal)value);
            }
        },
        ContractId1 {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getContractId1();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setContractId1((BigDecimal)value);
            }
        },
        UserBUSearchVO1 {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getUserBUSearchVO1();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        ProjectSearchVO1 {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getProjectSearchVO1();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        LookupVO1 {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getLookupVO1();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        LookupVO2 {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getLookupVO2();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        ProjectCustomerLOVVO1 {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getProjectCustomerLOVVO1();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        StaticYesorNoVO1 {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getStaticYesorNoVO1();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        StaticYesorNoVO2 {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getStaticYesorNoVO2();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        BOQHeaderVersionLOVVO1 {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getBOQHeaderVersionLOVVO1();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        ProjectSearchVO2 {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getProjectSearchVO2();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        ContractHeadersVO1 {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getContractHeadersVO1();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        ContractHeadersVO2 {
            public Object get(CandyBOQSearchVORowImpl obj) {
                return obj.getContractHeadersVO2();
            }

            public void put(CandyBOQSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(CandyBOQSearchVORowImpl object);

        public abstract void put(CandyBOQSearchVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BUNAME = AttributesEnum.BuName.index();
    public static final int TRANSCUSTOMERNAME =
        AttributesEnum.TransCustomerName.index();
    public static final int APPROVEDBY = AttributesEnum.ApprovedBy.index();
    public static final int APPROVEDDATE = AttributesEnum.ApprovedDate.index();
    public static final int BOQHEADERID = AttributesEnum.BoqHeaderId.index();
    public static final int BUSINESSUNITID =
        AttributesEnum.BusinessUnitId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CONTRACTNUMBER =
        AttributesEnum.ContractNumber.index();
    public static final int COGNOMEN = AttributesEnum.Cognomen.index();
    public static final int PROJECTNAME = AttributesEnum.ProjectName.index();
    public static final int PROJECTNUMBER =
        AttributesEnum.ProjectNumber.index();
    public static final int TRANSSTATUS = AttributesEnum.TransStatus.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int BUDGETTYPE = AttributesEnum.BudgetType.index();
    public static final int TRANSBUDGETTYPE =
        AttributesEnum.TransBudgetType.index();
    public static final int TRANSBASELINE =
        AttributesEnum.TransBaseLine.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int IBCNUMBER = AttributesEnum.IbcNumber.index();
    public static final int IBCREASON = AttributesEnum.IbcReason.index();
    public static final int IMPORTDATE = AttributesEnum.ImportDate.index();
    public static final int LASTUPDATEDBY =
        AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE =
        AttributesEnum.LastUpdatedDate.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int REVISIONDATE = AttributesEnum.RevisionDate.index();
    public static final int BUID = AttributesEnum.BuId.index();
    public static final int PROJECTID1 = AttributesEnum.ProjectId1.index();
    public static final int TRANSBUDGETCODE =
        AttributesEnum.TransBudgetCode.index();
    public static final int TOTALCANDYNETFINALAMOUNT =
        AttributesEnum.TotalCandyNetFinalAmount.index();
    public static final int TOTALCANDYNETFINALAMOUNT1 =
        AttributesEnum.TotalCandyNetFinalAmount1.index();
    public static final int TRANSABSOLUTEERROR =
        AttributesEnum.TransAbsoluteError.index();
    public static final int TRANSERRORPERCENTAGE =
        AttributesEnum.TransErrorPercentage.index();
    public static final int TOTALNETFINALAMOUNT =
        AttributesEnum.TotalNetFinalAmount.index();
    public static final int CURRENTFLAG = AttributesEnum.CurrentFlag.index();
    public static final int TRANSCANDYNETFINALAMOUNTTOTAL =
        AttributesEnum.TransCandyNetFinalAmountTotal.index();
    public static final int TRANSNETFINALAMOUNTTOTAL =
        AttributesEnum.TransNetFinalAmountTotal.index();
    public static final int BUNAME1 = AttributesEnum.BuName1.index();
    public static final int PROJECTNUMBER1 =
        AttributesEnum.ProjectNumber1.index();
    public static final int TRANSBUDGETTYPE1 =
        AttributesEnum.TransBudgetType1.index();
    public static final int TRANSPRECISION =
        AttributesEnum.TransPrecision.index();
    public static final int TRANSCURRENTFLAG =
        AttributesEnum.TransCurrentFlag.index();
    public static final int BASELINE = AttributesEnum.BaseLine.index();
    public static final int TRANSTOTALREVENUE =
        AttributesEnum.TransTotalRevenue.index();
    public static final int TRANSTOTALCOSTBUDGET =
        AttributesEnum.TransTotalCostBudget.index();
    public static final int TRANSFILENAME =
        AttributesEnum.TransFileName.index();
    public static final int CONTRACTID = AttributesEnum.ContractId.index();
    public static final int CONTRACTID1 = AttributesEnum.ContractId1.index();
    public static final int USERBUSEARCHVO1 =
        AttributesEnum.UserBUSearchVO1.index();
    public static final int PROJECTSEARCHVO1 =
        AttributesEnum.ProjectSearchVO1.index();
    public static final int LOOKUPVO1 = AttributesEnum.LookupVO1.index();
    public static final int LOOKUPVO2 = AttributesEnum.LookupVO2.index();
    public static final int PROJECTCUSTOMERLOVVO1 =
        AttributesEnum.ProjectCustomerLOVVO1.index();
    public static final int STATICYESORNOVO1 =
        AttributesEnum.StaticYesorNoVO1.index();
    public static final int STATICYESORNOVO2 =
        AttributesEnum.StaticYesorNoVO2.index();
    public static final int BOQHEADERVERSIONLOVVO1 =
        AttributesEnum.BOQHeaderVersionLOVVO1.index();
    public static final int PROJECTSEARCHVO2 =
        AttributesEnum.ProjectSearchVO2.index();
    public static final int CONTRACTHEADERSVO1 =
        AttributesEnum.ContractHeadersVO1.index();
    public static final int CONTRACTHEADERSVO2 =
        AttributesEnum.ContractHeadersVO2.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CandyBOQSearchVORowImpl() {
    }

    /**
     * Gets XxboqBillOfQtyHdrEO entity object.
     * @return the XxboqBillOfQtyHdrEO
     */
    public XxboqBillOfQtyHdrEOImpl getXxboqBillOfQtyHdrEO() {
        return (XxboqBillOfQtyHdrEOImpl)getEntity(0);
    }

    /**
     * Gets XxinvBusinessUnitsEO entity object.
     * @return the XxinvBusinessUnitsEO
     */
    public EntityImpl getXxinvBusinessUnitsEO() {
        return (EntityImpl)getEntity(1);
    }

    /**
     * Gets XxpjProjectsEO entity object.
     * @return the XxpjProjectsEO
     */
    public EntityImpl getXxpjProjectsEO() {
        return (EntityImpl)getEntity(2);
    }

    /**
     * Gets ContractHeadersEO entity object.
     * @return the ContractHeadersEO
     */
    public ContractHeadersEOImpl getContractHeadersEO() {
        return (ContractHeadersEOImpl)getEntity(3);
    }

    /**
     * Gets the attribute value for APPROVED_BY using the alias name ApprovedBy.
     * @return the APPROVED_BY
     */
    public String getApprovedBy() {
        return (String)getAttributeInternal(APPROVEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVED_BY using the alias name ApprovedBy.
     * @param value value to set the APPROVED_BY
     */
    public void setApprovedBy(String value) {
        setAttributeInternal(APPROVEDBY, value);
    }

    /**
     * Gets the attribute value for APPROVED_DATE using the alias name ApprovedDate.
     * @return the APPROVED_DATE
     */
    public Date getApprovedDate() {
        return (Date)getAttributeInternal(APPROVEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVED_DATE using the alias name ApprovedDate.
     * @param value value to set the APPROVED_DATE
     */
    public void setApprovedDate(Date value) {
        setAttributeInternal(APPROVEDDATE, value);
    }

    /**
     * Gets the attribute value for BOQ_HEADER_ID using the alias name BoqHeaderId.
     * @return the BOQ_HEADER_ID
     */
    public BigDecimal getBoqHeaderId() {
        return (BigDecimal)getAttributeInternal(BOQHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for BOQ_HEADER_ID using the alias name BoqHeaderId.
     * @param value value to set the BOQ_HEADER_ID
     */
    public void setBoqHeaderId(BigDecimal value) {
        setAttributeInternal(BOQHEADERID, value);
    }

    /**
     * Gets the attribute value for BUDGET_TYPE using the alias name BudgetType.
     * @return the BUDGET_TYPE
     */
    public String getBudgetType() {
        return (String)getAttributeInternal(BUDGETTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for BUDGET_TYPE using the alias name BudgetType.
     * @param value value to set the BUDGET_TYPE
     */
    public void setBudgetType(String value) {
        setAttributeInternal(BUDGETTYPE, value);
    }

    /**
     * Gets the attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @return the BUSINESS_UNIT_ID
     */
    public BigDecimal getBusinessUnitId() {
        return (BigDecimal)getAttributeInternal(BUSINESSUNITID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @param value value to set the BUSINESS_UNIT_ID
     */
    public void setBusinessUnitId(BigDecimal value) {
        setAttributeInternal(BUSINESSUNITID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for IBC_NUMBER using the alias name IbcNumber.
     * @return the IBC_NUMBER
     */
    public String getIbcNumber() {
        return (String)getAttributeInternal(IBCNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for IBC_NUMBER using the alias name IbcNumber.
     * @param value value to set the IBC_NUMBER
     */
    public void setIbcNumber(String value) {
        setAttributeInternal(IBCNUMBER, value);
    }

    /**
     * Gets the attribute value for IBC_REASON using the alias name IbcReason.
     * @return the IBC_REASON
     */
    public String getIbcReason() {
        return (String)getAttributeInternal(IBCREASON);
    }

    /**
     * Sets <code>value</code> as attribute value for IBC_REASON using the alias name IbcReason.
     * @param value value to set the IBC_REASON
     */
    public void setIbcReason(String value) {
        setAttributeInternal(IBCREASON, value);
    }

    /**
     * Gets the attribute value for IMPORT_DATE using the alias name ImportDate.
     * @return the IMPORT_DATE
     */
    public Date getImportDate() {
        return (Date)getAttributeInternal(IMPORTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for IMPORT_DATE using the alias name ImportDate.
     * @param value value to set the IMPORT_DATE
     */
    public void setImportDate(Date value) {
        setAttributeInternal(IMPORTDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public BigDecimal getProjectId() {
        return (BigDecimal)getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(BigDecimal value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for REVISION_DATE using the alias name RevisionDate.
     * @return the REVISION_DATE
     */
    public Date getRevisionDate() {
        return (Date)getAttributeInternal(REVISIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REVISION_DATE using the alias name RevisionDate.
     * @param value value to set the REVISION_DATE
     */
    public void setRevisionDate(Date value) {
        setAttributeInternal(REVISIONDATE, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for VERSION using the alias name Version.
     * @return the VERSION
     */
    public BigDecimal getVersion() {
        return (BigDecimal)getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION using the alias name Version.
     * @param value value to set the VERSION
     */
    public void setVersion(BigDecimal value) {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the attribute value for BU_NAME using the alias name BuName.
     * @return the BU_NAME
     */
    public String getBuName() {
        return (String)getAttributeInternal(BUNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for BU_NAME using the alias name BuName.
     * @param value value to set the BU_NAME
     */
    public void setBuName(String value) {
        setAttributeInternal(BUNAME, value);
    }

    /**
     * Gets the attribute value for BU_ID using the alias name BuId.
     * @return the BU_ID
     */
    public Number getBuId() {
        return (Number)getAttributeInternal(BUID);
    }

    /**
     * Sets <code>value</code> as attribute value for BU_ID using the alias name BuId.
     * @param value value to set the BU_ID
     */
    public void setBuId(Number value) {
        setAttributeInternal(BUID, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId1.
     * @return the PROJECT_ID
     */
    public Number getProjectId1() {
        return (Number)getAttributeInternal(PROJECTID1);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId1.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId1(Number value) {
        setAttributeInternal(PROJECTID1, value);
    }

    /**
     * Gets the attribute value for PROJECT_NAME using the alias name ProjectName.
     * @return the PROJECT_NAME
     */
    public String getProjectName() {
        return (String)getAttributeInternal(PROJECTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_NAME using the alias name ProjectName.
     * @param value value to set the PROJECT_NAME
     */
    public void setProjectName(String value) {
        setAttributeInternal(PROJECTNAME, value);
    }

    public String getStatusFromCode(String code) {
        String status = null;
        if (code != null) {
            if ("D".equals(code)) {
                status = "Draft";
            } else if ("I".equals(code)) {
                status = "Pending Approval";
            } else if ("A".equals(code)) {
                status = "Approved";
            } else if ("R".equals(code)) {
                status = "Rejected";
            } else if ("S".equals(code)) {
                status = "Submitted";
            } else if ("P".equals(code)) {
                status = "Posted";
            } else if ("RV".equals(code)) {
                status = "Reversed";
            } else if ("L".equals(code)) {
                status = "Loaded";
            } else if ("AC".equals(code)) {
                status = "Active";
            }
        }

        return status;
    }

    public String getTransStatus() {
        try {
            CandyBillofQuantityAMImpl applicationModule =
                (CandyBillofQuantityAMImpl)this.getApplicationModule();
            CommonUtilsAMImpl commAM =
                (CommonUtilsAMImpl)applicationModule.getCommonUtilsAM1();
            return commAM.getStatusFromCode(getStatus());
        } catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
        }
        return null;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransStatus.
     * @param value value to set the  TransStatus
     */
    public void setTransStatus(String value) {
        setAttributeInternal(TRANSSTATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransBudgetType.
     * @return the TransBudgetType
     */
    public String getTransBudgetType() {
        return (String)getAttributeInternal(TRANSBUDGETTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransBudgetType.
     * @param value value to set the  TransBudgetType
     */
    public void setTransBudgetType(String value) {
        setAttributeInternal(TRANSBUDGETTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransBudgetCode.
     * @return the TransBudgetCode
     */
    public String getTransBudgetCode() {
        return (String)getAttributeInternal(TRANSBUDGETCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransBudgetCode.
     * @param value value to set the  TransBudgetCode
     */
    public void setTransBudgetCode(String value) {
        setAttributeInternal(TRANSBUDGETCODE, value);
    }

    /**
     * Gets the attribute value for TOTAL_CANDY_NET_FINAL_AMOUNT using the alias name TotalCandyNetFinalAmount.
     * @return the TOTAL_CANDY_NET_FINAL_AMOUNT
     */
    public BigDecimal getTotalCandyNetFinalAmount() {
        return (BigDecimal)getAttributeInternal(TOTALCANDYNETFINALAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_CANDY_NET_FINAL_AMOUNT using the alias name TotalCandyNetFinalAmount.
     * @param value value to set the TOTAL_CANDY_NET_FINAL_AMOUNT
     */
    public void setTotalCandyNetFinalAmount(BigDecimal value) {
        setAttributeInternal(TOTALCANDYNETFINALAMOUNT, value);
    }

    /**
     * Gets the attribute value for TOTAL_CANDY_NET_FINAL_AMOUNT using the alias name TotalCandyNetFinalAmount1.
     * @return the TOTAL_CANDY_NET_FINAL_AMOUNT
     */
    public BigDecimal getTotalCandyNetFinalAmount1() {
        return (BigDecimal)getAttributeInternal(TOTALCANDYNETFINALAMOUNT1);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_CANDY_NET_FINAL_AMOUNT using the alias name TotalCandyNetFinalAmount1.
     * @param value value to set the TOTAL_CANDY_NET_FINAL_AMOUNT
     */
    public void setTotalCandyNetFinalAmount1(BigDecimal value) {
        setAttributeInternal(TOTALCANDYNETFINALAMOUNT1, value);
    }

    private Double getDiffPercentageFrom(Double value1, Double value2) {
        Double diff = value1 - value2;
        Double diffPerc = ((Math.abs(diff)) / value1) * 100;
        return diffPerc;
    }

    /**
     * Gets the attribute value for the calculated attribute TransAbsoluteError.
     * @return the TransAbsoluteError
     */
    public BigDecimal getTransAbsoluteError() {
        BigDecimal absError = null;
        try {
            if (getTransCandyNetFinalAmountTotal() != null &&
                getTransNetFinalAmountTotal() != null) {

                Double candyTotCostBud =
                    getTransCandyNetFinalAmountTotal().doubleValue();
                Double fussTotCostbud =
                    getTransNetFinalAmountTotal().doubleValue();
                if (candyTotCostBud != null && fussTotCostbud != null) {
                    absError =
                            new BigDecimal(candyTotCostBud.doubleValue() - fussTotCostbud.doubleValue());
                }
            }

        } catch (Exception e) {
            return null;
        }
        return absError;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransAbsoluteError.
     * @param value value to set the  TransAbsoluteError
     */
    public void setTransAbsoluteError(BigDecimal value) {
        setAttributeInternal(TRANSABSOLUTEERROR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransErrorPercentage.
     * @return the TransErrorPercentage
     */
    public BigDecimal getTransErrorPercentage() {
        BigDecimal absErrorPer = null;
        try {
            if (getTransCandyNetFinalAmountTotal() != null &&
                getTransNetFinalAmountTotal() != null) {

                Double candyTotCostBud =
                    getTransCandyNetFinalAmountTotal().doubleValue();
                Double fussTotCostbud =
                    getTransNetFinalAmountTotal().doubleValue();
                if (candyTotCostBud != null && fussTotCostbud != null) {
                    absErrorPer =
                            new BigDecimal(getDiffPercentageFrom(candyTotCostBud,
                                                                 fussTotCostbud));
                }
            }

        } catch (Exception e) {
            return null;
        }
        return absErrorPer;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransErrorPercentage.
     * @param value value to set the  TransErrorPercentage
     */
    public void setTransErrorPercentage(BigDecimal value) {
        setAttributeInternal(TRANSERRORPERCENTAGE, value);
    }

    /**
     * Gets the attribute value for TOTAL_NET_FINAL_AMOUNT using the alias name TotalNetFinalAmount.
     * @return the TOTAL_NET_FINAL_AMOUNT
     */
    public BigDecimal getTotalNetFinalAmount() {
        return (BigDecimal)getAttributeInternal(TOTALNETFINALAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_NET_FINAL_AMOUNT using the alias name TotalNetFinalAmount.
     * @param value value to set the TOTAL_NET_FINAL_AMOUNT
     */
    public void setTotalNetFinalAmount(BigDecimal value) {
        setAttributeInternal(TOTALNETFINALAMOUNT, value);
    }

    /**
     * Gets the attribute value for CURRENT_FLAG using the alias name CurrentFlag.
     * @return the CURRENT_FLAG
     */
    public String getCurrentFlag() {
        return (String)getAttributeInternal(CURRENTFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENT_FLAG using the alias name CurrentFlag.
     * @param value value to set the CURRENT_FLAG
     */
    public void setCurrentFlag(String value) {
        setAttributeInternal(CURRENTFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransCandyNetFinalAmountTotal.
     * @return the TransCandyNetFinalAmountTotal
     */
    public BigDecimal getTransCandyNetFinalAmountTotal() {
        return getTransNetFinalAmountTotal();
        //        return (BigDecimal) getAttributeInternal(TRANSCANDYNETFINALAMOUNTTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCandyNetFinalAmountTotal.
     * @param value value to set the  TransCandyNetFinalAmountTotal
     */
    public void setTransCandyNetFinalAmountTotal(BigDecimal value) {
        setAttributeInternal(TRANSCANDYNETFINALAMOUNTTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransNetFinalAmountTotal.
     * @return the TransNetFinalAmountTotal
     */
    public BigDecimal getTransNetFinalAmountTotal() {
        return (BigDecimal)getAttributeInternal(TRANSNETFINALAMOUNTTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransNetFinalAmountTotal.
     * @param value value to set the  TransNetFinalAmountTotal
     */
    public void setTransNetFinalAmountTotal(BigDecimal value) {
        setAttributeInternal(TRANSNETFINALAMOUNTTOTAL, value);
    }


    /**
     * Gets the attribute value for BU_NAME using the alias name BuName1.
     * @return the BU_NAME
     */
    public String getBuName1() {
        return (String)getAttributeInternal(BUNAME1);
    }

    /**
     * Sets <code>value</code> as attribute value for BU_NAME using the alias name BuName1.
     * @param value value to set the BU_NAME
     */
    public void setBuName1(String value) {
        setAttributeInternal(BUNAME1, value);
    }

    /**
     * Gets the attribute value for PROJECT_NUMBER using the alias name ProjectNumber1.
     * @return the PROJECT_NUMBER
     */
    public String getProjectNumber1() {
        return (String)getAttributeInternal(PROJECTNUMBER1);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_NUMBER using the alias name ProjectNumber1.
     * @param value value to set the PROJECT_NUMBER
     */
    public void setProjectNumber1(String value) {
        setAttributeInternal(PROJECTNUMBER1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransBudgetType1.
     * @return the TransBudgetType1
     */
    public String getTransBudgetType1() {
        return (String)getAttributeInternal(TRANSBUDGETTYPE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransBudgetType1.
     * @param value value to set the  TransBudgetType1
     */
    public void setTransBudgetType1(String value) {
        setAttributeInternal(TRANSBUDGETTYPE1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransPrecision.
     * @return the TransPrecision
     */
    public BigDecimal getTransPrecision() {
        return (BigDecimal)getAttributeInternal(TRANSPRECISION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransPrecision.
     * @param value value to set the  TransPrecision
     */
    public void setTransPrecision(BigDecimal value) {
        setAttributeInternal(TRANSPRECISION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransCustomerName.
     * @return the TransCustomerName
     */
    public String getTransCustomerName() {
        return (String)getAttributeInternal(TRANSCUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCustomerName.
     * @param value value to set the  TransCustomerName
     */
    public void setTransCustomerName(String value) {
        setAttributeInternal(TRANSCUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransCurrentFlag.
     * @return the TransCurrentFlag
     */
    public String getTransCurrentFlag() {
        return (String)getAttributeInternal(TRANSCURRENTFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCurrentFlag.
     * @param value value to set the  TransCurrentFlag
     */
    public void setTransCurrentFlag(String value) {
        setAttributeInternal(TRANSCURRENTFLAG, value);
    }

    /**
     * Gets the attribute value for BASE_LINE using the alias name BaseLine.
     * @return the BASE_LINE
     */
    public String getBaseLine() {
        return (String)getAttributeInternal(BASELINE);
    }

    /**
     * Sets <code>value</code> as attribute value for BASE_LINE using the alias name BaseLine.
     * @param value value to set the BASE_LINE
     */
    public void setBaseLine(String value) {
        setAttributeInternal(BASELINE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransTotalRevenue.
     * @return the TransTotalRevenue
     */
    public BigDecimal getTransTotalRevenue() {
        return (BigDecimal)getAttributeInternal(TRANSTOTALREVENUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransTotalRevenue.
     * @param value value to set the  TransTotalRevenue
     */
    public void setTransTotalRevenue(BigDecimal value) {
        setAttributeInternal(TRANSTOTALREVENUE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransTotalCostBudget.
     * @return the TransTotalCostBudget
     */
    public BigDecimal getTransTotalCostBudget() {
        return (BigDecimal)getAttributeInternal(TRANSTOTALCOSTBUDGET);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransTotalCostBudget.
     * @param value value to set the  TransTotalCostBudget
     */
    public void setTransTotalCostBudget(BigDecimal value) {
        setAttributeInternal(TRANSTOTALCOSTBUDGET, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransFileName.
     * @return the TransFileName
     */
    public String getTransFileName() {
        return (String)getAttributeInternal(TRANSFILENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransFileName.
     * @param value value to set the  TransFileName
     */
    public void setTransFileName(String value) {
        setAttributeInternal(TRANSFILENAME, value);
    }

    /**
     * Gets the attribute value for CONTRACT_ID using the alias name ContractId.
     * @return the CONTRACT_ID
     */
    public BigDecimal getContractId() {
        return (BigDecimal)getAttributeInternal(CONTRACTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_ID using the alias name ContractId.
     * @param value value to set the CONTRACT_ID
     */
    public void setContractId(BigDecimal value) {
        setAttributeInternal(CONTRACTID, value);
    }

    /**
     * Gets the attribute value for COGNOMEN using the alias name Cognomen.
     * @return the COGNOMEN
     */
    public String getCognomen() {
        return (String)getAttributeInternal(COGNOMEN);
    }

    /**
     * Sets <code>value</code> as attribute value for COGNOMEN using the alias name Cognomen.
     * @param value value to set the COGNOMEN
     */
    public void setCognomen(String value) {
        setAttributeInternal(COGNOMEN, value);
    }

    /**
     * Gets the attribute value for CONTRACT_ID using the alias name ContractId1.
     * @return the CONTRACT_ID
     */
    public BigDecimal getContractId1() {
        return (BigDecimal)getAttributeInternal(CONTRACTID1);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_ID using the alias name ContractId1.
     * @param value value to set the CONTRACT_ID
     */
    public void setContractId1(BigDecimal value) {
        setAttributeInternal(CONTRACTID1, value);
    }

    /**
     * Gets the attribute value for CONTRACT_NUMBER using the alias name ContractNumber.
     * @return the CONTRACT_NUMBER
     */
    public String getContractNumber() {
        return (String)getAttributeInternal(CONTRACTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_NUMBER using the alias name ContractNumber.
     * @param value value to set the CONTRACT_NUMBER
     */
    public void setContractNumber(String value) {
        setAttributeInternal(CONTRACTNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransBaseLine.
     * @return the TransBaseLine
     */
    public String getTransBaseLine() {
        return (String)getAttributeInternal(TRANSBASELINE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransBaseLine.
     * @param value value to set the  TransBaseLine
     */
    public void setTransBaseLine(String value) {
        setAttributeInternal(TRANSBASELINE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UserBUSearchVO1.
     */
    public RowSet getUserBUSearchVO1() {
        return (RowSet)getAttributeInternal(USERBUSEARCHVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProjectSearchVO1.
     */
    public RowSet getProjectSearchVO1() {
        return (RowSet)getAttributeInternal(PROJECTSEARCHVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupVO1.
     */
    public RowSet getLookupVO1() {
        return (RowSet)getAttributeInternal(LOOKUPVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupVO2.
     */
    public RowSet getLookupVO2() {
        return (RowSet)getAttributeInternal(LOOKUPVO2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProjectCustomerLOVVO1.
     */
    public RowSet getProjectCustomerLOVVO1() {
        return (RowSet)getAttributeInternal(PROJECTCUSTOMERLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StaticYesorNoVO1.
     */
    public RowSet getStaticYesorNoVO1() {
        return (RowSet)getAttributeInternal(STATICYESORNOVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StaticYesorNoVO2.
     */
    public RowSet getStaticYesorNoVO2() {
        return (RowSet)getAttributeInternal(STATICYESORNOVO2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BOQHeaderVersionLOVVO1.
     */
    public RowSet getBOQHeaderVersionLOVVO1() {
        return (RowSet)getAttributeInternal(BOQHEADERVERSIONLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProjectSearchVO2.
     */
    public RowSet getProjectSearchVO2() {
        return (RowSet)getAttributeInternal(PROJECTSEARCHVO2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ContractHeadersVO1.
     */
    public RowSet getContractHeadersVO1() {
        return (RowSet)getAttributeInternal(CONTRACTHEADERSVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ContractHeadersVO2.
     */
    public RowSet getContractHeadersVO2() {
        return (RowSet)getAttributeInternal(CONTRACTHEADERSVO2);
    }

    /**
     * Gets the attribute value for PROJECT_NUMBER using the alias name ProjectNumber.
     * @return the PROJECT_NUMBER
     */
    public String getProjectNumber() {
        return (String)getAttributeInternal(PROJECTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_NUMBER using the alias name ProjectNumber.
     * @param value value to set the PROJECT_NUMBER
     */
    public void setProjectNumber(String value) {
        setAttributeInternal(PROJECTNUMBER, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
