package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 13 15:07:09 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CandyBOQLinesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CandyBOQLinesVOImpl() {
    }
}
