package model.view;

import java.math.BigDecimal;

import model.entity.XxboqJobItemResourceEOImpl;

import model.entity.XxboqResourceItemsEOImpl;

import model.entity.XxboqResourceMasterGroupEOImpl;

import model.entity.XxboqResourceSubGroupEOImpl;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 30 17:14:27 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class JobItemResourceVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CreatedBy {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        },
        CreationDate {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        },
        ItemId {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getItemId();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setItemId((Number)value);
            }
        },
        JobItemAnalysisId {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getJobItemAnalysisId();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setJobItemAnalysisId((Number)value);
            }
        },
        JobItemResourceId {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getJobItemResourceId();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setJobItemResourceId((Number)value);
            }
        },
        LastUpdatedBy {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        },
        LastUpdatedDate {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        },
        MaintenancePercentage {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getMaintenancePercentage();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setMaintenancePercentage((Number)value);
            }
        },
        Quantity {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getQuantity();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setQuantity((Number)value);
            }
        },
        ResourceGroupId {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getResourceGroupId();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setResourceGroupId((Number)value);
            }
        },
        ResourceSubGroupId {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getResourceSubGroupId();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setResourceSubGroupId((Number)value);
            }
        },
        SparesPercentage {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getSparesPercentage();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setSparesPercentage((Number)value);
            }
        },
        WastagePercentage {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getWastagePercentage();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setWastagePercentage((Number)value);
            }
        },
        TransItemNumber {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getTransItemNumber();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setTransItemNumber((String)value);
            }
        },
        TransGroup {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getTransGroup();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setTransGroup((String)value);
            }
        },
        TransSubGroup {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getTransSubGroup();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setTransSubGroup((String)value);
            }
        },
        TransType {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getTransType();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setTransType((String)value);
            }
        },
        TransUOM {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getTransUOM();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setTransUOM((String)value);
            }
        },
        TransItemDescription {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getTransItemDescription();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setTransItemDescription((String)value);
            }
        },
        TransItemRate {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getTransItemRate();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setTransItemRate((BigDecimal)value);
            }
        },
        TransDeleteLineFlag {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getTransDeleteLineFlag();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setTransDeleteLineFlag((Boolean)value);
            }
        },
        TransAmount {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getTransAmount();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setTransAmount((BigDecimal)value);
            }
        },
        TransTypeCode {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getTransTypeCode();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setTransTypeCode((String)value);
            }
        },
        ItemId1 {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getItemId1();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setItemId1((BigDecimal)value);
            }
        },
        ItemRate {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getItemRate();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setItemRate((BigDecimal)value);
            }
        },
        ItemCode {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getItemCode();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setItemCode((String)value);
            }
        },
        ItemDescription {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getItemDescription();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setItemDescription((String)value);
            }
        },
        ResourceGroupId1 {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getResourceGroupId1();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setResourceGroupId1((BigDecimal)value);
            }
        },
        ResourceSubGroupId1 {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getResourceSubGroupId1();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setResourceSubGroupId1((BigDecimal)value);
            }
        },
        Uom {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getUom();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setUom((String)value);
            }
        },
        ResourceGroupId2 {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getResourceGroupId2();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setResourceGroupId2((BigDecimal)value);
            }
        },
        ResourceType {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getResourceType();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setResourceType((String)value);
            }
        },
        ResourceTypeCode {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getResourceTypeCode();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setResourceTypeCode((String)value);
            }
        },
        ResourceGroup {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getResourceGroup();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setResourceGroup((String)value);
            }
        },
        ResourceSubGroupId2 {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getResourceSubGroupId2();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setResourceSubGroupId2((BigDecimal)value);
            }
        },
        ResourceSubGroup {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getResourceSubGroup();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setResourceSubGroup((String)value);
            }
        },
        UnitRate {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getUnitRate();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setUnitRate((BigDecimal)value);
            }
        },
        JobItemAnalysisVO {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getJobItemAnalysisVO();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        ProjectJobResourcesVO1 {
            public Object get(JobItemResourceVORowImpl obj) {
                return obj.getProjectJobResourcesVO1();
            }

            public void put(JobItemResourceVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(JobItemResourceVORowImpl object);

        public abstract void put(JobItemResourceVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int JOBITEMANALYSISID =
        AttributesEnum.JobItemAnalysisId.index();
    public static final int JOBITEMRESOURCEID =
        AttributesEnum.JobItemResourceId.index();
    public static final int LASTUPDATEDBY =
        AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE =
        AttributesEnum.LastUpdatedDate.index();
    public static final int MAINTENANCEPERCENTAGE =
        AttributesEnum.MaintenancePercentage.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int RESOURCEGROUPID =
        AttributesEnum.ResourceGroupId.index();
    public static final int RESOURCESUBGROUPID =
        AttributesEnum.ResourceSubGroupId.index();
    public static final int SPARESPERCENTAGE =
        AttributesEnum.SparesPercentage.index();
    public static final int WASTAGEPERCENTAGE =
        AttributesEnum.WastagePercentage.index();
    public static final int TRANSITEMNUMBER =
        AttributesEnum.TransItemNumber.index();
    public static final int TRANSGROUP = AttributesEnum.TransGroup.index();
    public static final int TRANSSUBGROUP =
        AttributesEnum.TransSubGroup.index();
    public static final int TRANSTYPE = AttributesEnum.TransType.index();
    public static final int TRANSUOM = AttributesEnum.TransUOM.index();
    public static final int TRANSITEMDESCRIPTION =
        AttributesEnum.TransItemDescription.index();
    public static final int TRANSITEMRATE =
        AttributesEnum.TransItemRate.index();
    public static final int TRANSDELETELINEFLAG =
        AttributesEnum.TransDeleteLineFlag.index();
    public static final int TRANSAMOUNT = AttributesEnum.TransAmount.index();
    public static final int TRANSTYPECODE =
        AttributesEnum.TransTypeCode.index();
    public static final int ITEMID1 = AttributesEnum.ItemId1.index();
    public static final int ITEMRATE = AttributesEnum.ItemRate.index();
    public static final int ITEMCODE = AttributesEnum.ItemCode.index();
    public static final int ITEMDESCRIPTION =
        AttributesEnum.ItemDescription.index();
    public static final int RESOURCEGROUPID1 =
        AttributesEnum.ResourceGroupId1.index();
    public static final int RESOURCESUBGROUPID1 =
        AttributesEnum.ResourceSubGroupId1.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int RESOURCEGROUPID2 =
        AttributesEnum.ResourceGroupId2.index();
    public static final int RESOURCETYPE = AttributesEnum.ResourceType.index();
    public static final int RESOURCETYPECODE =
        AttributesEnum.ResourceTypeCode.index();
    public static final int RESOURCEGROUP =
        AttributesEnum.ResourceGroup.index();
    public static final int RESOURCESUBGROUPID2 =
        AttributesEnum.ResourceSubGroupId2.index();
    public static final int RESOURCESUBGROUP =
        AttributesEnum.ResourceSubGroup.index();
    public static final int UNITRATE = AttributesEnum.UnitRate.index();
    public static final int JOBITEMANALYSISVO =
        AttributesEnum.JobItemAnalysisVO.index();
    public static final int PROJECTJOBRESOURCESVO1 =
        AttributesEnum.ProjectJobResourcesVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public JobItemResourceVORowImpl() {
    }

    /**
     * Gets XxboqJobItemResourceEO entity object.
     * @return the XxboqJobItemResourceEO
     */
    public XxboqJobItemResourceEOImpl getXxboqJobItemResourceEO() {
        return (XxboqJobItemResourceEOImpl)getEntity(0);
    }


    /**
     * Gets XxboqResourceItemsEO entity object.
     * @return the XxboqResourceItemsEO
     */
    public XxboqResourceItemsEOImpl getXxboqResourceItemsEO() {
        return (XxboqResourceItemsEOImpl)getEntity(1);
    }

    /**
     * Gets XxboqResourceMasterGroupEO entity object.
     * @return the XxboqResourceMasterGroupEO
     */
    public XxboqResourceMasterGroupEOImpl getXxboqResourceMasterGroupEO() {
        return (XxboqResourceMasterGroupEOImpl)getEntity(2);
    }

    /**
     * Gets XxboqResourceSubGroupEO entity object.
     * @return the XxboqResourceSubGroupEO
     */
    public XxboqResourceSubGroupEOImpl getXxboqResourceSubGroupEO() {
        return (XxboqResourceSubGroupEOImpl)getEntity(3);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for ITEM_ID using the alias name ItemId.
     * @return the ITEM_ID
     */
    public Number getItemId() {
        return (Number)getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_ID using the alias name ItemId.
     * @param value value to set the ITEM_ID
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for JOB_ITEM_ANALYSIS_ID using the alias name JobItemAnalysisId.
     * @return the JOB_ITEM_ANALYSIS_ID
     */
    public Number getJobItemAnalysisId() {
        return (Number)getAttributeInternal(JOBITEMANALYSISID);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_ITEM_ANALYSIS_ID using the alias name JobItemAnalysisId.
     * @param value value to set the JOB_ITEM_ANALYSIS_ID
     */
    public void setJobItemAnalysisId(Number value) {
        setAttributeInternal(JOBITEMANALYSISID, value);
    }

    /**
     * Gets the attribute value for JOB_ITEM_RESOURCE_ID using the alias name JobItemResourceId.
     * @return the JOB_ITEM_RESOURCE_ID
     */
    public Number getJobItemResourceId() {
        return (Number)getAttributeInternal(JOBITEMRESOURCEID);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_ITEM_RESOURCE_ID using the alias name JobItemResourceId.
     * @param value value to set the JOB_ITEM_RESOURCE_ID
     */
    public void setJobItemResourceId(Number value) {
        setAttributeInternal(JOBITEMRESOURCEID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for MAINTENANCE_PERCENTAGE using the alias name MaintenancePercentage.
     * @return the MAINTENANCE_PERCENTAGE
     */
    public Number getMaintenancePercentage() {
        return (Number)getAttributeInternal(MAINTENANCEPERCENTAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for MAINTENANCE_PERCENTAGE using the alias name MaintenancePercentage.
     * @param value value to set the MAINTENANCE_PERCENTAGE
     */
    public void setMaintenancePercentage(Number value) {
        setAttributeInternal(MAINTENANCEPERCENTAGE, value);
    }


    /**
     * Gets the attribute value for QUANTITY using the alias name Quantity.
     * @return the QUANTITY
     */
    public Number getQuantity() {
        return (Number)getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity.
     * @param value value to set the QUANTITY
     */
    public void setQuantity(Number value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for RESOURCE_GROUP_ID using the alias name ResourceGroupId.
     * @return the RESOURCE_GROUP_ID
     */
    public Number getResourceGroupId() {
        return (Number)getAttributeInternal(RESOURCEGROUPID);
    }

    /**
     * Sets <code>value</code> as attribute value for RESOURCE_GROUP_ID using the alias name ResourceGroupId.
     * @param value value to set the RESOURCE_GROUP_ID
     */
    public void setResourceGroupId(Number value) {
        setAttributeInternal(RESOURCEGROUPID, value);
    }

    /**
     * Gets the attribute value for RESOURCE_SUB_GROUP_ID using the alias name ResourceSubGroupId.
     * @return the RESOURCE_SUB_GROUP_ID
     */
    public Number getResourceSubGroupId() {
        return (Number)getAttributeInternal(RESOURCESUBGROUPID);
    }

    /**
     * Sets <code>value</code> as attribute value for RESOURCE_SUB_GROUP_ID using the alias name ResourceSubGroupId.
     * @param value value to set the RESOURCE_SUB_GROUP_ID
     */
    public void setResourceSubGroupId(Number value) {
        setAttributeInternal(RESOURCESUBGROUPID, value);
    }

    /**
     * Gets the attribute value for SPARES_PERCENTAGE using the alias name SparesPercentage.
     * @return the SPARES_PERCENTAGE
     */
    public Number getSparesPercentage() {
        return (Number)getAttributeInternal(SPARESPERCENTAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for SPARES_PERCENTAGE using the alias name SparesPercentage.
     * @param value value to set the SPARES_PERCENTAGE
     */
    public void setSparesPercentage(Number value) {
        setAttributeInternal(SPARESPERCENTAGE, value);
    }

    /**
     * Gets the attribute value for WASTAGE_PERCENTAGE using the alias name WastagePercentage.
     * @return the WASTAGE_PERCENTAGE
     */
    public Number getWastagePercentage() {
        return (Number)getAttributeInternal(WASTAGEPERCENTAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for WASTAGE_PERCENTAGE using the alias name WastagePercentage.
     * @param value value to set the WASTAGE_PERCENTAGE
     */
    public void setWastagePercentage(Number value) {
        setAttributeInternal(WASTAGEPERCENTAGE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransItemNumber.
     * @return the TransItemNumber
     */
    public String getTransItemNumber() {
        if (getItemCode() != null) {
            return getItemCode();
        }
        return (String)getAttributeInternal(TRANSITEMNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransItemNumber.
     * @param value value to set the  TransItemNumber
     */
    public void setTransItemNumber(String value) {
        setAttributeInternal(TRANSITEMNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransGroup.
     * @return the TransGroup
     */
    public String getTransGroup() {
        if (getResourceGroup() != null) {
            return getResourceGroup();
        }
        return (String)getAttributeInternal(TRANSGROUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransGroup.
     * @param value value to set the  TransGroup
     */
    public void setTransGroup(String value) {
        setAttributeInternal(TRANSGROUP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransSubGroup.
     * @return the TransSubGroup
     */
    public String getTransSubGroup() {
        if (getResourceSubGroup() != null) {
            return getResourceSubGroup();
        }
        return (String)getAttributeInternal(TRANSSUBGROUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransSubGroup.
     * @param value value to set the  TransSubGroup
     */
    public void setTransSubGroup(String value) {
        setAttributeInternal(TRANSSUBGROUP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransType.
     * @return the TransType
     */
    public String getTransType() {
        if (getResourceType() != null) {
            return getResourceType();
        }
        return (String)getAttributeInternal(TRANSTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransType.
     * @param value value to set the  TransType
     */
    public void setTransType(String value) {
        setAttributeInternal(TRANSTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransUOM.
     * @return the TransUOM
     */
    public String getTransUOM() {
        if (getUom() != null) {
            return getUom();
        }
        return (String)getAttributeInternal(TRANSUOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransUOM.
     * @param value value to set the  TransUOM
     */
    public void setTransUOM(String value) {
        setAttributeInternal(TRANSUOM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransItemDescription.
     * @return the TransItemDescription
     */
    public String getTransItemDescription() {
        if (getItemDescription() != null) {
            return getItemDescription();
        }
        return (String)getAttributeInternal(TRANSITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransItemDescription.
     * @param value value to set the  TransItemDescription
     */
    public void setTransItemDescription(String value) {
        setAttributeInternal(TRANSITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransItemRate.
     * @return the TransItemRate
     */
    public BigDecimal getTransItemRate() {
        Object rate = getUnitRate();
        if (getUnitRate() != null) {
            return getUnitRate();
        }
        return (BigDecimal)getAttributeInternal(TRANSITEMRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransItemRate.
     * @param value value to set the  TransItemRate
     */
    public void setTransItemRate(BigDecimal value) {
        setAttributeInternal(TRANSITEMRATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransDeleteLineFlag.
     * @return the TransDeleteLineFlag
     */
    public Boolean getTransDeleteLineFlag() {
        return (Boolean)getAttributeInternal(TRANSDELETELINEFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransDeleteLineFlag.
     * @param value value to set the  TransDeleteLineFlag
     */
    public void setTransDeleteLineFlag(Boolean value) {
        setAttributeInternal(TRANSDELETELINEFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransAmount.
     * @return the TransAmount
     */
    public BigDecimal getTransAmount() {
        BigDecimal totAmount = null;
        Double rate =
            getItemRate() != null ? getItemRate().doubleValue() : 0.0;
        Double quantity =
            getQuantity() != null ? getQuantity().doubleValue() : 0.0;

        Double perct =
            "E".equals(getResourceTypeCode()) ? getSparesPercentage().doubleValue() +
            getMaintenancePercentage().doubleValue() :
            "M".equals(getResourceTypeCode()) ?
            getWastagePercentage().doubleValue() : 0.0;
        //        Double sparesPerct =
        //            getSparesPercentage() != null ? getSparesPercentage().doubleValue() :
        //            0.0;
        //        Double maintPerct =
        //            getMaintenancePercentage() != null ? getMaintenancePercentage().doubleValue() :
        //            0.0;
        //        Double watagePerct =
        //            getWastagePercentage() != null ? getWastagePercentage().doubleValue() :
        //            0.0;

        Double perctAmount = (rate * quantity) * (perct / 100);
        totAmount = new BigDecimal((rate * quantity) + (perctAmount));
        return totAmount;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransAmount.
     * @param value value to set the  TransAmount
     */
    public void setTransAmount(BigDecimal value) {
        setAttributeInternal(TRANSAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransTypeCode.
     * @return the TransTypeCode
     */
    public String getTransTypeCode() {
        if (getResourceTypeCode() != null) {
            return getResourceTypeCode();
        }
        return (String)getAttributeInternal(TRANSTYPECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransTypeCode.
     * @param value value to set the  TransTypeCode
     */
    public void setTransTypeCode(String value) {
        setAttributeInternal(TRANSTYPECODE, value);
    }

    /**
     * Gets the attribute value for ITEM_ID using the alias name ItemId1.
     * @return the ITEM_ID
     */
    public BigDecimal getItemId1() {
        return (BigDecimal)getAttributeInternal(ITEMID1);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_ID using the alias name ItemId1.
     * @param value value to set the ITEM_ID
     */
    public void setItemId1(BigDecimal value) {
        setAttributeInternal(ITEMID1, value);
    }

    /**
     * Gets the attribute value for ITEM_RATE using the alias name ItemRate.
     * @return the ITEM_RATE
     */
    public BigDecimal getItemRate() {
        return (BigDecimal)getAttributeInternal(ITEMRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_RATE using the alias name ItemRate.
     * @param value value to set the ITEM_RATE
     */
    public void setItemRate(BigDecimal value) {
        setAttributeInternal(ITEMRATE, value);
    }

    /**
     * Gets the attribute value for ITEM_CODE using the alias name ItemCode.
     * @return the ITEM_CODE
     */
    public String getItemCode() {
        return (String)getAttributeInternal(ITEMCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_CODE using the alias name ItemCode.
     * @param value value to set the ITEM_CODE
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**
     * Gets the attribute value for ITEM_DESCRIPTION using the alias name ItemDescription.
     * @return the ITEM_DESCRIPTION
     */
    public String getItemDescription() {
        return (String)getAttributeInternal(ITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_DESCRIPTION using the alias name ItemDescription.
     * @param value value to set the ITEM_DESCRIPTION
     */
    public void setItemDescription(String value) {
        setAttributeInternal(ITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for RESOURCE_GROUP_ID using the alias name ResourceGroupId1.
     * @return the RESOURCE_GROUP_ID
     */
    public BigDecimal getResourceGroupId1() {
        return (BigDecimal)getAttributeInternal(RESOURCEGROUPID1);
    }

    /**
     * Sets <code>value</code> as attribute value for RESOURCE_GROUP_ID using the alias name ResourceGroupId1.
     * @param value value to set the RESOURCE_GROUP_ID
     */
    public void setResourceGroupId1(BigDecimal value) {
        setAttributeInternal(RESOURCEGROUPID1, value);
    }

    /**
     * Gets the attribute value for RESOURCE_SUB_GROUP_ID using the alias name ResourceSubGroupId1.
     * @return the RESOURCE_SUB_GROUP_ID
     */
    public BigDecimal getResourceSubGroupId1() {
        return (BigDecimal)getAttributeInternal(RESOURCESUBGROUPID1);
    }

    /**
     * Sets <code>value</code> as attribute value for RESOURCE_SUB_GROUP_ID using the alias name ResourceSubGroupId1.
     * @param value value to set the RESOURCE_SUB_GROUP_ID
     */
    public void setResourceSubGroupId1(BigDecimal value) {
        setAttributeInternal(RESOURCESUBGROUPID1, value);
    }

    /**
     * Gets the attribute value for UOM using the alias name Uom.
     * @return the UOM
     */
    public String getUom() {
        return (String)getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as attribute value for UOM using the alias name Uom.
     * @param value value to set the UOM
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for RESOURCE_GROUP_ID using the alias name ResourceGroupId2.
     * @return the RESOURCE_GROUP_ID
     */
    public BigDecimal getResourceGroupId2() {
        return (BigDecimal)getAttributeInternal(RESOURCEGROUPID2);
    }

    /**
     * Sets <code>value</code> as attribute value for RESOURCE_GROUP_ID using the alias name ResourceGroupId2.
     * @param value value to set the RESOURCE_GROUP_ID
     */
    public void setResourceGroupId2(BigDecimal value) {
        setAttributeInternal(RESOURCEGROUPID2, value);
    }

    /**
     * Gets the attribute value for RESOURCE_TYPE using the alias name ResourceType.
     * @return the RESOURCE_TYPE
     */
    public String getResourceType() {
        return (String)getAttributeInternal(RESOURCETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for RESOURCE_TYPE using the alias name ResourceType.
     * @param value value to set the RESOURCE_TYPE
     */
    public void setResourceType(String value) {
        setAttributeInternal(RESOURCETYPE, value);
    }

    /**
     * Gets the attribute value for RESOURCE_TYPE_CODE using the alias name ResourceTypeCode.
     * @return the RESOURCE_TYPE_CODE
     */
    public String getResourceTypeCode() {
        return (String)getAttributeInternal(RESOURCETYPECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for RESOURCE_TYPE_CODE using the alias name ResourceTypeCode.
     * @param value value to set the RESOURCE_TYPE_CODE
     */
    public void setResourceTypeCode(String value) {
        setAttributeInternal(RESOURCETYPECODE, value);
    }

    /**
     * Gets the attribute value for RESOURCE_GROUP using the alias name ResourceGroup.
     * @return the RESOURCE_GROUP
     */
    public String getResourceGroup() {
        return (String)getAttributeInternal(RESOURCEGROUP);
    }

    /**
     * Sets <code>value</code> as attribute value for RESOURCE_GROUP using the alias name ResourceGroup.
     * @param value value to set the RESOURCE_GROUP
     */
    public void setResourceGroup(String value) {
        setAttributeInternal(RESOURCEGROUP, value);
    }

    /**
     * Gets the attribute value for RESOURCE_SUB_GROUP_ID using the alias name ResourceSubGroupId2.
     * @return the RESOURCE_SUB_GROUP_ID
     */
    public BigDecimal getResourceSubGroupId2() {
        return (BigDecimal)getAttributeInternal(RESOURCESUBGROUPID2);
    }

    /**
     * Sets <code>value</code> as attribute value for RESOURCE_SUB_GROUP_ID using the alias name ResourceSubGroupId2.
     * @param value value to set the RESOURCE_SUB_GROUP_ID
     */
    public void setResourceSubGroupId2(BigDecimal value) {
        setAttributeInternal(RESOURCESUBGROUPID2, value);
    }

    /**
     * Gets the attribute value for RESOURCE_SUB_GROUP using the alias name ResourceSubGroup.
     * @return the RESOURCE_SUB_GROUP
     */
    public String getResourceSubGroup() {
        return (String)getAttributeInternal(RESOURCESUBGROUP);
    }

    /**
     * Sets <code>value</code> as attribute value for RESOURCE_SUB_GROUP using the alias name ResourceSubGroup.
     * @param value value to set the RESOURCE_SUB_GROUP
     */
    public void setResourceSubGroup(String value) {
        setAttributeInternal(RESOURCESUBGROUP, value);
    }


    /**
     * Gets the attribute value for UNIT_RATE using the alias name UnitRate.
     * @return the UNIT_RATE
     */
    public BigDecimal getUnitRate() {
        return (BigDecimal)getAttributeInternal(UNITRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_RATE using the alias name UnitRate.
     * @param value value to set the UNIT_RATE
     */
    public void setUnitRate(BigDecimal value) {
        setAttributeInternal(UNITRATE, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link JobItemAnalysisVO.
     */
    public Row getJobItemAnalysisVO() {
        return (Row)getAttributeInternal(JOBITEMANALYSISVO);
    }

    /**
     * Sets the master-detail link JobItemAnalysisVO between this object and <code>value</code>.
     */
    public void setJobItemAnalysisVO(Row value) {
        setAttributeInternal(JOBITEMANALYSISVO, value);
    }


    /**
     * Gets the view accessor <code>RowSet</code> ProjectJobResourcesVO1.
     */
    public RowSet getProjectJobResourcesVO1() {
        return (RowSet)getAttributeInternal(PROJECTJOBRESOURCESVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
