package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 05 12:39:18 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PlanningScheduleHdrVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PlanningScheduleHdrVOImpl() {
    }
}
