package model.viewentity;

import java.math.BigDecimal;

import java.sql.Date;

import model.reportview.BoqPcHdrViewVORowImpl;

import oracle.jbo.Key;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 08 18:48:50 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxboqPcLinesVEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PcHeaderId {
            public Object get(XxboqPcLinesVEOImpl obj) {
                return obj.getPcHeaderId();
            }

            public void put(XxboqPcLinesVEOImpl obj, Object value) {
                obj.setPcHeaderId((BigDecimal)value);
            }
        },
        ProjectId {
            public Object get(XxboqPcLinesVEOImpl obj) {
                return obj.getProjectId();
            }

            public void put(XxboqPcLinesVEOImpl obj, Object value) {
                obj.setProjectId((BigDecimal)value);
            }
        },
        PcDocumentNum {
            public Object get(XxboqPcLinesVEOImpl obj) {
                return obj.getPcDocumentNum();
            }

            public void put(XxboqPcLinesVEOImpl obj, Object value) {
                obj.setPcDocumentNum((String)value);
            }
        },
        Description {
            public Object get(XxboqPcLinesVEOImpl obj) {
                return obj.getDescription();
            }

            public void put(XxboqPcLinesVEOImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        },
        Amount {
            public Object get(XxboqPcLinesVEOImpl obj) {
                return obj.getAmount();
            }

            public void put(XxboqPcLinesVEOImpl obj, Object value) {
                obj.setAmount((BigDecimal)value);
            }
        },
        Month {
            public Object get(XxboqPcLinesVEOImpl obj) {
                return obj.getMonth();
            }

            public void put(XxboqPcLinesVEOImpl obj, Object value) {
                obj.setMonth((Date)value);
            }
        },
        Period {
            public Object get(XxboqPcLinesVEOImpl obj) {
                return obj.getPeriod();
            }

            public void put(XxboqPcLinesVEOImpl obj, Object value) {
                obj.setPeriod((String)value);
            }
        },
        Remarks {
            public Object get(XxboqPcLinesVEOImpl obj) {
                return obj.getRemarks();
            }

            public void put(XxboqPcLinesVEOImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        },
        XxboqPcHdrVEO {
            public Object get(XxboqPcLinesVEOImpl obj) {
                return obj.getXxboqPcHdrVEO();
            }

            public void put(XxboqPcLinesVEOImpl obj, Object value) {
                obj.setXxboqPcHdrVEO((XxboqPcHdrVEOImpl)value);
            }
        },
        BoqPcHdrViewVO {
            public Object get(XxboqPcLinesVEOImpl obj) {
                return obj.getBoqPcHdrViewVO();
            }

            public void put(XxboqPcLinesVEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxboqPcLinesVEOImpl object);

        public abstract void put(XxboqPcLinesVEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PCHEADERID = AttributesEnum.PcHeaderId.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int PCDOCUMENTNUM =
        AttributesEnum.PcDocumentNum.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int MONTH = AttributesEnum.Month.index();
    public static final int PERIOD = AttributesEnum.Period.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int XXBOQPCHDRVEO =
        AttributesEnum.XxboqPcHdrVEO.index();
    public static final int BOQPCHDRVIEWVO =
        AttributesEnum.BoqPcHdrViewVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxboqPcLinesVEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.viewentity.XxboqPcLinesVEO");
    }

    /**
     * Gets the attribute value for PcHeaderId, using the alias name PcHeaderId.
     * @return the PcHeaderId
     */
    public BigDecimal getPcHeaderId() {
        return (BigDecimal)getAttributeInternal(PCHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PcHeaderId.
     * @param value value to set the PcHeaderId
     */
    public void setPcHeaderId(BigDecimal value) {
        setAttributeInternal(PCHEADERID, value);
    }

    /**
     * Gets the attribute value for ProjectId, using the alias name ProjectId.
     * @return the ProjectId
     */
    public BigDecimal getProjectId() {
        return (BigDecimal)getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProjectId.
     * @param value value to set the ProjectId
     */
    public void setProjectId(BigDecimal value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for PcDocumentNum, using the alias name PcDocumentNum.
     * @return the PcDocumentNum
     */
    public String getPcDocumentNum() {
        return (String)getAttributeInternal(PCDOCUMENTNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for PcDocumentNum.
     * @param value value to set the PcDocumentNum
     */
    public void setPcDocumentNum(String value) {
        setAttributeInternal(PCDOCUMENTNUM, value);
    }

    /**
     * Gets the attribute value for Description, using the alias name Description.
     * @return the Description
     */
    public String getDescription() {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Description.
     * @param value value to set the Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for Amount, using the alias name Amount.
     * @return the Amount
     */
    public BigDecimal getAmount() {
        return (BigDecimal)getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Amount.
     * @param value value to set the Amount
     */
    public void setAmount(BigDecimal value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for Month, using the alias name Month.
     * @return the Month
     */
    public Date getMonth() {
        return (Date)getAttributeInternal(MONTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Month.
     * @param value value to set the Month
     */
    public void setMonth(Date value) {
        setAttributeInternal(MONTH, value);
    }

    /**
     * Gets the attribute value for Period, using the alias name Period.
     * @return the Period
     */
    public String getPeriod() {
        return (String)getAttributeInternal(PERIOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for Period.
     * @param value value to set the Period
     */
    public void setPeriod(String value) {
        setAttributeInternal(PERIOD, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity XxboqPcHdrVEOImpl.
     */
    public XxboqPcHdrVEOImpl getXxboqPcHdrVEO() {
        return (XxboqPcHdrVEOImpl)getAttributeInternal(XXBOQPCHDRVEO);
    }

    /**
     * Sets <code>value</code> as the associated entity XxboqPcHdrVEOImpl.
     */
    public void setXxboqPcHdrVEO(XxboqPcHdrVEOImpl value) {
        setAttributeInternal(XXBOQPCHDRVEO, value);
    }

    /**
     * Uses the link BoqPcHdrviewToLinesViewVL to return rows of BoqPcLinesViewVO
     */
    public BoqPcHdrViewVORowImpl getBoqPcHdrViewVO() {
        return (BoqPcHdrViewVORowImpl)getAttributeInternal(BOQPCHDRVIEWVO);
    }

    /**
     * @param pcHeaderId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal pcHeaderId) {
        return new Key(new Object[] { pcHeaderId });
    }

}
