package model.entity;

import java.math.BigDecimal;

import java.sql.Date;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 29 09:39:24 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxboqResourceSubGroupEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ResourceSubGroupId {
            public Object get(XxboqResourceSubGroupEOImpl obj) {
                return obj.getResourceSubGroupId();
            }

            public void put(XxboqResourceSubGroupEOImpl obj, Object value) {
                obj.setResourceSubGroupId((BigDecimal)value);
            }
        },
        ResourceGroupId {
            public Object get(XxboqResourceSubGroupEOImpl obj) {
                return obj.getResourceGroupId();
            }

            public void put(XxboqResourceSubGroupEOImpl obj, Object value) {
                obj.setResourceGroupId((BigDecimal)value);
            }
        },
        BuId {
            public Object get(XxboqResourceSubGroupEOImpl obj) {
                return obj.getBuId();
            }

            public void put(XxboqResourceSubGroupEOImpl obj, Object value) {
                obj.setBuId((BigDecimal)value);
            }
        },
        ResourceType {
            public Object get(XxboqResourceSubGroupEOImpl obj) {
                return obj.getResourceType();
            }

            public void put(XxboqResourceSubGroupEOImpl obj, Object value) {
                obj.setResourceType((String)value);
            }
        },
        ResourceTypeCode {
            public Object get(XxboqResourceSubGroupEOImpl obj) {
                return obj.getResourceTypeCode();
            }

            public void put(XxboqResourceSubGroupEOImpl obj, Object value) {
                obj.setResourceTypeCode((String)value);
            }
        },
        ResourceGroup {
            public Object get(XxboqResourceSubGroupEOImpl obj) {
                return obj.getResourceGroup();
            }

            public void put(XxboqResourceSubGroupEOImpl obj, Object value) {
                obj.setResourceGroup((String)value);
            }
        },
        ResourceSubGroup {
            public Object get(XxboqResourceSubGroupEOImpl obj) {
                return obj.getResourceSubGroup();
            }

            public void put(XxboqResourceSubGroupEOImpl obj, Object value) {
                obj.setResourceSubGroup((String)value);
            }
        },
        SubGroupDescription {
            public Object get(XxboqResourceSubGroupEOImpl obj) {
                return obj.getSubGroupDescription();
            }

            public void put(XxboqResourceSubGroupEOImpl obj, Object value) {
                obj.setSubGroupDescription((String)value);
            }
        },
        ExpenditureCategory {
            public Object get(XxboqResourceSubGroupEOImpl obj) {
                return obj.getExpenditureCategory();
            }

            public void put(XxboqResourceSubGroupEOImpl obj, Object value) {
                obj.setExpenditureCategory((String)value);
            }
        },
        CreationDate {
            public Object get(XxboqResourceSubGroupEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(XxboqResourceSubGroupEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        CreatedBy {
            public Object get(XxboqResourceSubGroupEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(XxboqResourceSubGroupEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        LastUpdatedDate {
            public Object get(XxboqResourceSubGroupEOImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(XxboqResourceSubGroupEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        LastUpdatedBy {
            public Object get(XxboqResourceSubGroupEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(XxboqResourceSubGroupEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        XxboqResourceMasterGroupEO {
            public Object get(XxboqResourceSubGroupEOImpl obj) {
                return obj.getXxboqResourceMasterGroupEO();
            }

            public void put(XxboqResourceSubGroupEOImpl obj, Object value) {
                obj.setXxboqResourceMasterGroupEO((XxboqResourceMasterGroupEOImpl)value);
            }
        },
        XxboqResourceItemsEO {
            public Object get(XxboqResourceSubGroupEOImpl obj) {
                return obj.getXxboqResourceItemsEO();
            }

            public void put(XxboqResourceSubGroupEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxboqResourceSubGroupEOImpl object);

        public abstract void put(XxboqResourceSubGroupEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int RESOURCESUBGROUPID =
        AttributesEnum.ResourceSubGroupId.index();
    public static final int RESOURCEGROUPID =
        AttributesEnum.ResourceGroupId.index();
    public static final int BUID = AttributesEnum.BuId.index();
    public static final int RESOURCETYPE = AttributesEnum.ResourceType.index();
    public static final int RESOURCETYPECODE =
        AttributesEnum.ResourceTypeCode.index();
    public static final int RESOURCEGROUP =
        AttributesEnum.ResourceGroup.index();
    public static final int RESOURCESUBGROUP =
        AttributesEnum.ResourceSubGroup.index();
    public static final int SUBGROUPDESCRIPTION =
        AttributesEnum.SubGroupDescription.index();
    public static final int EXPENDITURECATEGORY =
        AttributesEnum.ExpenditureCategory.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDDATE =
        AttributesEnum.LastUpdatedDate.index();
    public static final int LASTUPDATEDBY =
        AttributesEnum.LastUpdatedBy.index();
    public static final int XXBOQRESOURCEMASTERGROUPEO =
        AttributesEnum.XxboqResourceMasterGroupEO.index();
    public static final int XXBOQRESOURCEITEMSEO =
        AttributesEnum.XxboqResourceItemsEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxboqResourceSubGroupEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject =
                    EntityDefImpl.findDefObject("model.entity.XxboqResourceSubGroupEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for ResourceSubGroupId, using the alias name ResourceSubGroupId.
     * @return the ResourceSubGroupId
     */
    public BigDecimal getResourceSubGroupId() {
        return (BigDecimal)getAttributeInternal(RESOURCESUBGROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ResourceSubGroupId.
     * @param value value to set the ResourceSubGroupId
     */
    public void setResourceSubGroupId(BigDecimal value) {
        setAttributeInternal(RESOURCESUBGROUPID, value);
    }

    /**
     * Gets the attribute value for ResourceGroupId, using the alias name ResourceGroupId.
     * @return the ResourceGroupId
     */
    public BigDecimal getResourceGroupId() {
        return (BigDecimal)getAttributeInternal(RESOURCEGROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ResourceGroupId.
     * @param value value to set the ResourceGroupId
     */
    public void setResourceGroupId(BigDecimal value) {
        setAttributeInternal(RESOURCEGROUPID, value);
    }

    /**
     * Gets the attribute value for BuId, using the alias name BuId.
     * @return the BuId
     */
    public BigDecimal getBuId() {
        return (BigDecimal)getAttributeInternal(BUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuId.
     * @param value value to set the BuId
     */
    public void setBuId(BigDecimal value) {
        setAttributeInternal(BUID, value);
    }

    /**
     * Gets the attribute value for ResourceType, using the alias name ResourceType.
     * @return the ResourceType
     */
    public String getResourceType() {
        return (String)getAttributeInternal(RESOURCETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ResourceType.
     * @param value value to set the ResourceType
     */
    public void setResourceType(String value) {
        setAttributeInternal(RESOURCETYPE, value);
    }

    /**
     * Gets the attribute value for ResourceTypeCode, using the alias name ResourceTypeCode.
     * @return the ResourceTypeCode
     */
    public String getResourceTypeCode() {
        return (String)getAttributeInternal(RESOURCETYPECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ResourceTypeCode.
     * @param value value to set the ResourceTypeCode
     */
    public void setResourceTypeCode(String value) {
        setAttributeInternal(RESOURCETYPECODE, value);
    }

    /**
     * Gets the attribute value for ResourceGroup, using the alias name ResourceGroup.
     * @return the ResourceGroup
     */
    public String getResourceGroup() {
        return (String)getAttributeInternal(RESOURCEGROUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for ResourceGroup.
     * @param value value to set the ResourceGroup
     */
    public void setResourceGroup(String value) {
        setAttributeInternal(RESOURCEGROUP, value);
    }

    /**
     * Gets the attribute value for ResourceSubGroup, using the alias name ResourceSubGroup.
     * @return the ResourceSubGroup
     */
    public String getResourceSubGroup() {
        return (String)getAttributeInternal(RESOURCESUBGROUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for ResourceSubGroup.
     * @param value value to set the ResourceSubGroup
     */
    public void setResourceSubGroup(String value) {
        setAttributeInternal(RESOURCESUBGROUP, value);
    }

    /**
     * Gets the attribute value for SubGroupDescription, using the alias name SubGroupDescription.
     * @return the SubGroupDescription
     */
    public String getSubGroupDescription() {
        return (String)getAttributeInternal(SUBGROUPDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubGroupDescription.
     * @param value value to set the SubGroupDescription
     */
    public void setSubGroupDescription(String value) {
        setAttributeInternal(SUBGROUPDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ExpenditureCategory, using the alias name ExpenditureCategory.
     * @return the ExpenditureCategory
     */
    public String getExpenditureCategory() {
        return (String)getAttributeInternal(EXPENDITURECATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpenditureCategory.
     * @param value value to set the ExpenditureCategory
     */
    public void setExpenditureCategory(String value) {
        setAttributeInternal(EXPENDITURECATEGORY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @return the associated entity XxboqResourceMasterGroupEOImpl.
     */
    public XxboqResourceMasterGroupEOImpl getXxboqResourceMasterGroupEO() {
        return (XxboqResourceMasterGroupEOImpl)getAttributeInternal(XXBOQRESOURCEMASTERGROUPEO);
    }

    /**
     * Sets <code>value</code> as the associated entity XxboqResourceMasterGroupEOImpl.
     */
    public void setXxboqResourceMasterGroupEO(XxboqResourceMasterGroupEOImpl value) {
        setAttributeInternal(XXBOQRESOURCEMASTERGROUPEO, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getXxboqResourceItemsEO() {
        return (RowIterator)getAttributeInternal(XXBOQRESOURCEITEMSEO);
    }


    /**
     * @param resourceSubGroupId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal resourceSubGroupId) {
        return new Key(new Object[] { resourceSubGroupId });
    }

    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seq =
            new SequenceImpl("XXBOQ_RESOURCE_SUB_GROUP_S", getDBTransaction());
        setResourceSubGroupId(new BigDecimal(seq.getSequenceNumber().toString()));
    }

    private static final byte USERNAME_HISTORY_TYPE = 13;

    @Override
    protected Object getHistoryContextForAttribute(AttributeDefImpl attr) {
        if (attr.getHistoryKind() == USERNAME_HISTORY_TYPE) {
            // Custom History type logic goes here
            return (String)((Map)ADFContext.getCurrent().getSessionScope().get("userMap")).get("UserName");
        }
        return super.getHistoryContextForAttribute(attr);
    }
}
