package model.searchview;

import java.math.BigDecimal;

import java.sql.Date;

import model.applicationmodule.BillingDetailsAMImpl;
import model.applicationmodule.BillofQuantityAMImpl;
import model.applicationmodule.CommonUtilsAMImpl;

import model.entity.XxboqCertifiedDetailsEOImpl;

import model.masterentity.ContractHeadersEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 27 14:49:14 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CertifiedQtySearchVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        BuName {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getBuName();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setBuName((String)value);
            }
        },
        TransCustomerName {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getTransCustomerName();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setTransCustomerName((String)value);
            }
        },
        ContractNumber {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getContractNumber();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setContractNumber((String)value);
            }
        }
        ,
        Cognomen {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getCognomen();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setCognomen((String)value);
            }
        }
        ,
        ProjectName {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getProjectName();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setProjectName((String)value);
            }
        },
        ProjectNumber1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getProjectNumber1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setProjectNumber1((String)value);
            }
        },
        CertifiedDocumentNum1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getCertifiedDocumentNum1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setCertifiedDocumentNum1((String)value);
            }
        },
        Version {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getVersion();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setVersion((BigDecimal)value);
            }
        },
        PeriodOfMeasure1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getPeriodOfMeasure1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setPeriodOfMeasure1((String)value);
            }
        },
        CertifiedStatus {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getCertifiedStatus();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setCertifiedStatus((String)value);
            }
        },
        TransCurrentFlag {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getTransCurrentFlag();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setTransCurrentFlag((String)value);
            }
        },
        BusinessUnitId {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getBusinessUnitId();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setBusinessUnitId((BigDecimal)value);
            }
        },
        CreatedBy {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        },
        CreationDate {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        },
        LastUpdatedBy {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        },
        LastUpdatedDate {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        },
        PeriodOfMeasure {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getPeriodOfMeasure();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setPeriodOfMeasure((String)value);
            }
        },
        ProjectId {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getProjectId();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setProjectId((BigDecimal)value);
            }
        },
        CertifiedApprovedDate {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getCertifiedApprovedDate();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setCertifiedApprovedDate((Date)value);
            }
        },
        CertifiedDocumentDate {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getCertifiedDocumentDate();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setCertifiedDocumentDate((Date)value);
            }
        },
        CertifiedDocumentNum {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getCertifiedDocumentNum();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setCertifiedDocumentNum((String)value);
            }
        },
        CertifiedHeaderId {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getCertifiedHeaderId();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setCertifiedHeaderId((BigDecimal)value);
            }
        },
        TransBusinessUnit {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getTransBusinessUnit();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setTransBusinessUnit((String)value);
            }
        },
        TransProject {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getTransProject();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setTransProject((String)value);
            }
        },
        TransPrjStartDate {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getTransPrjStartDate();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setTransPrjStartDate((Date)value);
            }
        },
        TransPrjEndDate {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getTransPrjEndDate();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setTransPrjEndDate((Date)value);
            }
        },
        BusinessUnitId1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getBusinessUnitId1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setBusinessUnitId1((BigDecimal)value);
            }
        },
        BuId {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getBuId();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setBuId((Number)value);
            }
        },
        ProjectId1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getProjectId1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setProjectId1((Number)value);
            }
        },
        ProjectNumber {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getProjectNumber();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setProjectNumber((String)value);
            }
        },
        CertifiedocumentDate1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getCertifiedocumentDate1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setCertifiedocumentDate1((Date)value);
            }
        },
        TransProjectName {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getTransProjectName();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setTransProjectName((String)value);
            }
        },
        TransSearchPrjStart {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getTransSearchPrjStart();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setTransSearchPrjStart((Date)value);
            }
        },
        TransSearchPrjEnd {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getTransSearchPrjEnd();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setTransSearchPrjEnd((Date)value);
            }
        },
        CertifiedApprovedBy {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getCertifiedApprovedBy();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setCertifiedApprovedBy((String)value);
            }
        },
        TransStatus {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getTransStatus();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setTransStatus((String)value);
            }
        },
        InvoiceHeaderId {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getInvoiceHeaderId();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setInvoiceHeaderId((BigDecimal)value);
            }
        },
        MasterBoqHeaderId {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getMasterBoqHeaderId();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setMasterBoqHeaderId((BigDecimal)value);
            }
        },
        MasterCertHeaderId {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getMasterCertHeaderId();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setMasterCertHeaderId((BigDecimal)value);
            }
        },
        MasterInvoiceHeaderId {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getMasterInvoiceHeaderId();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setMasterInvoiceHeaderId((BigDecimal)value);
            }
        },
        ParentCertHeaderId {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getParentCertHeaderId();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setParentCertHeaderId((BigDecimal)value);
            }
        },
        TransStartDate {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getTransStartDate();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setTransStartDate((Date)value);
            }
        },
        BoqHeaderId {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getBoqHeaderId();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setBoqHeaderId((BigDecimal)value);
            }
        },
        MasterCertHeaderId1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getMasterCertHeaderId1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setMasterCertHeaderId1((BigDecimal)value);
            }
        },
        MasterInvoiceHeaderId1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getMasterInvoiceHeaderId1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setMasterInvoiceHeaderId1((BigDecimal)value);
            }
        },
        ParentCertHeaderId1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getParentCertHeaderId1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setParentCertHeaderId1((BigDecimal)value);
            }
        },
        TransCurrentCumltTotal {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getTransCurrentCumltTotal();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setTransCurrentCumltTotal((BigDecimal)value);
            }
        },
        TransCumltTotal {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getTransCumltTotal();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setTransCumltTotal((BigDecimal)value);
            }
        },
        TransActualAmnt {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getTransActualAmnt();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setTransActualAmnt((BigDecimal)value);
            }
        },
        TransInvoiceNumber {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getTransInvoiceNumber();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setTransInvoiceNumber((String)value);
            }
        },
        TransInvoiceVersion {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getTransInvoiceVersion();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setTransInvoiceVersion((BigDecimal)value);
            }
        },
        CurrentFlag {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getCurrentFlag();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setCurrentFlag((String)value);
            }
        },
        BuName1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getBuName1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setBuName1((String)value);
            }
        },
        TransPrecision {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getTransPrecision();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setTransPrecision((BigDecimal)value);
            }
        },
        TransPreviousTotal {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getTransPreviousTotal();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setTransPreviousTotal((BigDecimal)value);
            }
        },
        TransBOQVersion {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getTransBOQVersion();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setTransBOQVersion((BigDecimal)value);
            }
        },
        ContractId {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getContractId();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setContractId((BigDecimal)value);
            }
        }
        ,
        ContractId1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getContractId1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setContractId1((BigDecimal)value);
            }
        }
        ,
        ValuationDate {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getValuationDate();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setValuationDate((Date)value);
            }
        }
        ,
        UserBusinessUnitsVO1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getUserBusinessUnitsVO1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        PrjProjectsVO1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getPrjProjectsVO1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        AgreementMonthsVO1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getAgreementMonthsVO1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        CertifiedQtyDetailsVO1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getCertifiedQtyDetailsVO1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        PrjProjectsVO2 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getPrjProjectsVO2();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        AgreementMonthsVO2 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getAgreementMonthsVO2();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        UserBusinessUnitsVO2 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getUserBusinessUnitsVO2();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        MaxProjectCertifiedDocDateScrVO1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getMaxProjectCertifiedDocDateScrVO1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        ProjectCustomerLOVVO1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getProjectCustomerLOVVO1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        ProjectSearchVO1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getProjectSearchVO1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        CertifiedVersionLOVVO1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getCertifiedVersionLOVVO1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        StaticYesorNoVO1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getStaticYesorNoVO1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        LookupVO1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getLookupVO1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ContractHeadersVO1 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getContractHeadersVO1();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ContractHeadersVO2 {
            public Object get(CertifiedQtySearchVORowImpl obj) {
                return obj.getContractHeadersVO2();
            }

            public void put(CertifiedQtySearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(CertifiedQtySearchVORowImpl object);

        public abstract void put(CertifiedQtySearchVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BUNAME = AttributesEnum.BuName.index();
    public static final int TRANSCUSTOMERNAME =
        AttributesEnum.TransCustomerName.index();
    public static final int CONTRACTNUMBER = AttributesEnum.ContractNumber.index();
    public static final int COGNOMEN = AttributesEnum.Cognomen.index();
    public static final int PROJECTNAME = AttributesEnum.ProjectName.index();
    public static final int PROJECTNUMBER1 =
        AttributesEnum.ProjectNumber1.index();
    public static final int CERTIFIEDDOCUMENTNUM1 =
        AttributesEnum.CertifiedDocumentNum1.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int PERIODOFMEASURE1 =
        AttributesEnum.PeriodOfMeasure1.index();
    public static final int CERTIFIEDSTATUS =
        AttributesEnum.CertifiedStatus.index();
    public static final int TRANSCURRENTFLAG =
        AttributesEnum.TransCurrentFlag.index();
    public static final int BUSINESSUNITID =
        AttributesEnum.BusinessUnitId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY =
        AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE =
        AttributesEnum.LastUpdatedDate.index();
    public static final int PERIODOFMEASURE =
        AttributesEnum.PeriodOfMeasure.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int CERTIFIEDAPPROVEDDATE =
        AttributesEnum.CertifiedApprovedDate.index();
    public static final int CERTIFIEDDOCUMENTDATE =
        AttributesEnum.CertifiedDocumentDate.index();
    public static final int CERTIFIEDDOCUMENTNUM =
        AttributesEnum.CertifiedDocumentNum.index();
    public static final int CERTIFIEDHEADERID =
        AttributesEnum.CertifiedHeaderId.index();
    public static final int TRANSBUSINESSUNIT =
        AttributesEnum.TransBusinessUnit.index();
    public static final int TRANSPROJECT = AttributesEnum.TransProject.index();
    public static final int TRANSPRJSTARTDATE =
        AttributesEnum.TransPrjStartDate.index();
    public static final int TRANSPRJENDDATE =
        AttributesEnum.TransPrjEndDate.index();
    public static final int BUSINESSUNITID1 =
        AttributesEnum.BusinessUnitId1.index();
    public static final int BUID = AttributesEnum.BuId.index();
    public static final int PROJECTID1 = AttributesEnum.ProjectId1.index();
    public static final int PROJECTNUMBER =
        AttributesEnum.ProjectNumber.index();
    public static final int CERTIFIEDOCUMENTDATE1 =
        AttributesEnum.CertifiedocumentDate1.index();
    public static final int TRANSPROJECTNAME =
        AttributesEnum.TransProjectName.index();
    public static final int TRANSSEARCHPRJSTART =
        AttributesEnum.TransSearchPrjStart.index();
    public static final int TRANSSEARCHPRJEND =
        AttributesEnum.TransSearchPrjEnd.index();
    public static final int CERTIFIEDAPPROVEDBY =
        AttributesEnum.CertifiedApprovedBy.index();
    public static final int TRANSSTATUS = AttributesEnum.TransStatus.index();
    public static final int INVOICEHEADERID =
        AttributesEnum.InvoiceHeaderId.index();
    public static final int MASTERBOQHEADERID =
        AttributesEnum.MasterBoqHeaderId.index();
    public static final int MASTERCERTHEADERID =
        AttributesEnum.MasterCertHeaderId.index();
    public static final int MASTERINVOICEHEADERID =
        AttributesEnum.MasterInvoiceHeaderId.index();
    public static final int PARENTCERTHEADERID =
        AttributesEnum.ParentCertHeaderId.index();
    public static final int TRANSSTARTDATE =
        AttributesEnum.TransStartDate.index();
    public static final int BOQHEADERID = AttributesEnum.BoqHeaderId.index();
    public static final int MASTERCERTHEADERID1 =
        AttributesEnum.MasterCertHeaderId1.index();
    public static final int MASTERINVOICEHEADERID1 =
        AttributesEnum.MasterInvoiceHeaderId1.index();
    public static final int PARENTCERTHEADERID1 =
        AttributesEnum.ParentCertHeaderId1.index();
    public static final int TRANSCURRENTCUMLTTOTAL =
        AttributesEnum.TransCurrentCumltTotal.index();
    public static final int TRANSCUMLTTOTAL =
        AttributesEnum.TransCumltTotal.index();
    public static final int TRANSACTUALAMNT =
        AttributesEnum.TransActualAmnt.index();
    public static final int TRANSINVOICENUMBER =
        AttributesEnum.TransInvoiceNumber.index();
    public static final int TRANSINVOICEVERSION =
        AttributesEnum.TransInvoiceVersion.index();
    public static final int CURRENTFLAG = AttributesEnum.CurrentFlag.index();
    public static final int BUNAME1 = AttributesEnum.BuName1.index();
    public static final int TRANSPRECISION = AttributesEnum.TransPrecision.index();
    public static final int TRANSPREVIOUSTOTAL = AttributesEnum.TransPreviousTotal.index();
    public static final int TRANSBOQVERSION = AttributesEnum.TransBOQVersion.index();
    public static final int CONTRACTID = AttributesEnum.ContractId.index();
    public static final int CONTRACTID1 = AttributesEnum.ContractId1.index();
    public static final int VALUATIONDATE = AttributesEnum.ValuationDate.index();
    public static final int USERBUSINESSUNITSVO1 = AttributesEnum.UserBusinessUnitsVO1.index();
    public static final int PRJPROJECTSVO1 = AttributesEnum.PrjProjectsVO1.index();
    public static final int AGREEMENTMONTHSVO1 = AttributesEnum.AgreementMonthsVO1.index();
    public static final int CERTIFIEDQTYDETAILSVO1 = AttributesEnum.CertifiedQtyDetailsVO1.index();
    public static final int PRJPROJECTSVO2 = AttributesEnum.PrjProjectsVO2.index();
    public static final int AGREEMENTMONTHSVO2 = AttributesEnum.AgreementMonthsVO2.index();
    public static final int USERBUSINESSUNITSVO2 = AttributesEnum.UserBusinessUnitsVO2.index();
    public static final int MAXPROJECTCERTIFIEDDOCDATESCRVO1 = AttributesEnum.MaxProjectCertifiedDocDateScrVO1.index();
    public static final int PROJECTCUSTOMERLOVVO1 = AttributesEnum.ProjectCustomerLOVVO1.index();
    public static final int PROJECTSEARCHVO1 = AttributesEnum.ProjectSearchVO1.index();
    public static final int CERTIFIEDVERSIONLOVVO1 = AttributesEnum.CertifiedVersionLOVVO1.index();
    public static final int STATICYESORNOVO1 = AttributesEnum.StaticYesorNoVO1.index();
    public static final int LOOKUPVO1 = AttributesEnum.LookupVO1.index();
    public static final int CONTRACTHEADERSVO1 = AttributesEnum.ContractHeadersVO1.index();
    public static final int CONTRACTHEADERSVO2 = AttributesEnum.ContractHeadersVO2.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CertifiedQtySearchVORowImpl() {
    }

    /**
     * Gets XxboqCertifiedetailsEO entity object.
     * @return the XxboqCertifiedetailsEO
     */
    public XxboqCertifiedDetailsEOImpl getXxboqCertifiedetailsEO() {
        return (XxboqCertifiedDetailsEOImpl)getEntity(0);
    }

    /**
     * Gets XxinvBusinessUnitsEO entity object.
     * @return the XxinvBusinessUnitsEO
     */
    public EntityImpl getXxinvBusinessUnitsEO() {
        return (EntityImpl)getEntity(1);
    }

    /**
     * Gets XxpjProjectsEO entity object.
     * @return the XxpjProjectsEO
     */
    public EntityImpl getXxpjProjectsEO() {
        return (EntityImpl)getEntity(2);
    }

    /**
     * Gets ContractHeadersEO entity object.
     * @return the ContractHeadersEO
     */
    public ContractHeadersEOImpl getContractHeadersEO() {
        return (ContractHeadersEOImpl)getEntity(3);
    }

    /**
     * Gets the attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @return the BUSINESS_UNIT_ID
     */
    public BigDecimal getBusinessUnitId() {
        return (BigDecimal)getAttributeInternal(BUSINESSUNITID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @param value value to set the BUSINESS_UNIT_ID
     */
    public void setBusinessUnitId(BigDecimal value) {
        setAttributeInternal(BUSINESSUNITID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for PERIOD_OF_MEASURE using the alias name PeriodOfMeasure.
     * @return the PERIOD_OF_MEASURE
     */
    public String getPeriodOfMeasure() {
        return (String)getAttributeInternal(PERIODOFMEASURE);
    }

    /**
     * Sets <code>value</code> as attribute value for PERIOD_OF_MEASURE using the alias name PeriodOfMeasure.
     * @param value value to set the PERIOD_OF_MEASURE
     */
    public void setPeriodOfMeasure(String value) {
        setAttributeInternal(PERIODOFMEASURE, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public BigDecimal getProjectId() {
        return (BigDecimal)getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(BigDecimal value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for CERTIFIED_APPROVED_DATE using the alias name CertifiedApprovedDate.
     * @return the CERTIFIED_APPROVED_DATE
     */
    public Date getCertifiedApprovedDate() {
        return (Date)getAttributeInternal(CERTIFIEDAPPROVEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CERTIFIED_APPROVED_DATE using the alias name CertifiedApprovedDate.
     * @param value value to set the CERTIFIED_APPROVED_DATE
     */
    public void setCertifiedApprovedDate(Date value) {
        setAttributeInternal(CERTIFIEDAPPROVEDDATE, value);
    }

    /**
     * Gets the attribute value for CERTIFIED_DOCUMENT_DATE using the alias name CertifiedDocumentDate.
     * @return the CERTIFIED_DOCUMENT_DATE
     */
    public Date getCertifiedDocumentDate() {
        return (Date)getAttributeInternal(CERTIFIEDDOCUMENTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CERTIFIED_DOCUMENT_DATE using the alias name CertifiedDocumentDate.
     * @param value value to set the CERTIFIED_DOCUMENT_DATE
     */
    public void setCertifiedDocumentDate(Date value) {
        setAttributeInternal(CERTIFIEDDOCUMENTDATE, value);
    }

    /**
     * Gets the attribute value for CERTIFIED_DOCUMENT_NUM using the alias name CertifiedDocumentNum.
     * @return the CERTIFIED_DOCUMENT_NUM
     */
    public String getCertifiedDocumentNum() {
        return (String)getAttributeInternal(CERTIFIEDDOCUMENTNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for CERTIFIED_DOCUMENT_NUM using the alias name CertifiedDocumentNum.
     * @param value value to set the CERTIFIED_DOCUMENT_NUM
     */
    public void setCertifiedDocumentNum(String value) {
        setAttributeInternal(CERTIFIEDDOCUMENTNUM, value);
    }

    /**
     * Gets the attribute value for CERTIFIED_HEADER_ID using the alias name CertifiedHeaderId.
     * @return the CERTIFIED_HEADER_ID
     */
    public BigDecimal getCertifiedHeaderId() {
        return (BigDecimal)getAttributeInternal(CERTIFIEDHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CERTIFIED_HEADER_ID using the alias name CertifiedHeaderId.
     * @param value value to set the CERTIFIED_HEADER_ID
     */
    public void setCertifiedHeaderId(BigDecimal value) {
        setAttributeInternal(CERTIFIEDHEADERID, value);
    }

    /**
     * Gets the attribute value for CERTIFIED_STATUS using the alias name CertifiedStatus.
     * @return the CERTIFIED_STATUS
     */
    public String getCertifiedStatus() {
        return (String)getAttributeInternal(CERTIFIEDSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for CERTIFIED_STATUS using the alias name CertifiedStatus.
     * @param value value to set the CERTIFIED_STATUS
     */
    public void setCertifiedStatus(String value) {
        setAttributeInternal(CERTIFIEDSTATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransBusinessUnit.
     * @return the TransBusinessUnit
     */
    public String getTransBusinessUnit() {
        return (String)getAttributeInternal(TRANSBUSINESSUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransBusinessUnit.
     * @param value value to set the  TransBusinessUnit
     */
    public void setTransBusinessUnit(String value) {
        setAttributeInternal(TRANSBUSINESSUNIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransProject.
     * @return the TransProject
     */
    public String getTransProject() {
        return (String)getAttributeInternal(TRANSPROJECT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransProject.
     * @param value value to set the  TransProject
     */
    public void setTransProject(String value) {
        setAttributeInternal(TRANSPROJECT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransPrjStartDate.
     * @return the TransPrjStartDate
     */
    public Date getTransPrjStartDate() {
        return (Date)getAttributeInternal(TRANSPRJSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransPrjStartDate.
     * @param value value to set the  TransPrjStartDate
     */
    public void setTransPrjStartDate(Date value) {
        setAttributeInternal(TRANSPRJSTARTDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransPrjEndDate.
     * @return the TransPrjEndDate
     */
    public Date getTransPrjEndDate() {
        return (Date)getAttributeInternal(TRANSPRJENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransPrjEndDate.
     * @param value value to set the  TransPrjEndDate
     */
    public void setTransPrjEndDate(Date value) {
        setAttributeInternal(TRANSPRJENDDATE, value);
    }

    /**
     * Gets the attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId1.
     * @return the BUSINESS_UNIT_ID
     */
    public BigDecimal getBusinessUnitId1() {
        return (BigDecimal)getAttributeInternal(BUSINESSUNITID1);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId1.
     * @param value value to set the BUSINESS_UNIT_ID
     */
    public void setBusinessUnitId1(BigDecimal value) {
        setAttributeInternal(BUSINESSUNITID1, value);
    }

    /**
     * Gets the attribute value for BU_NAME using the alias name BuName.
     * @return the BU_NAME
     */
    public String getBuName() {
        return (String)getAttributeInternal(BUNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for BU_NAME using the alias name BuName.
     * @param value value to set the BU_NAME
     */
    public void setBuName(String value) {
        setAttributeInternal(BUNAME, value);
    }

    /**
     * Gets the attribute value for BU_ID using the alias name BuId.
     * @return the BU_ID
     */
    public Number getBuId() {
        return (Number)getAttributeInternal(BUID);
    }

    /**
     * Sets <code>value</code> as attribute value for BU_ID using the alias name BuId.
     * @param value value to set the BU_ID
     */
    public void setBuId(Number value) {
        setAttributeInternal(BUID, value);
    }

    /**
     * Gets the attribute value for PROJECT_NAME using the alias name ProjectName.
     * @return the PROJECT_NAME
     */
    public String getProjectName() {
        return (String)getAttributeInternal(PROJECTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_NAME using the alias name ProjectName.
     * @param value value to set the PROJECT_NAME
     */
    public void setProjectName(String value) {
        setAttributeInternal(PROJECTNAME, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId1.
     * @return the PROJECT_ID
     */
    public Number getProjectId1() {
        return (Number)getAttributeInternal(PROJECTID1);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId1.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId1(Number value) {
        setAttributeInternal(PROJECTID1, value);
    }

    /**
     * Gets the attribute value for PROJECT_NUMBER using the alias name ProjectNumber.
     * @return the PROJECT_NUMBER
     */
    public String getProjectNumber() {
        return (String)getAttributeInternal(PROJECTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_NUMBER using the alias name ProjectNumber.
     * @param value value to set the PROJECT_NUMBER
     */
    public void setProjectNumber(String value) {
        setAttributeInternal(PROJECTNUMBER, value);
    }

    /**
     * Gets the attribute value for PROJECT_NUMBER using the alias name ProjectNumber1.
     * @return the PROJECT_NUMBER
     */
    public String getProjectNumber1() {
        return (String)getAttributeInternal(PROJECTNUMBER1);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_NUMBER using the alias name ProjectNumber1.
     * @param value value to set the PROJECT_NUMBER
     */
    public void setProjectNumber1(String value) {
        setAttributeInternal(PROJECTNUMBER1, value);
    }

    /**
     * Gets the attribute value for PERIOD_OF_MEASURE using the alias name PeriodOfMeasure1.
     * @return the PERIOD_OF_MEASURE
     */
    public String getPeriodOfMeasure1() {
        return (String)getAttributeInternal(PERIODOFMEASURE1);
    }

    /**
     * Sets <code>value</code> as attribute value for PERIOD_OF_MEASURE using the alias name PeriodOfMeasure1.
     * @param value value to set the PERIOD_OF_MEASURE
     */
    public void setPeriodOfMeasure1(String value) {
        setAttributeInternal(PERIODOFMEASURE1, value);
    }

    /**
     * Gets the attribute value for CERTIFIED_DOCUMENT_NUM using the alias name CertifiedDocumentNum1.
     * @return the CERTIFIED_DOCUMENT_NUM
     */
    public String getCertifiedDocumentNum1() {
        return (String)getAttributeInternal(CERTIFIEDDOCUMENTNUM1);
    }

    /**
     * Sets <code>value</code> as attribute value for CERTIFIED_DOCUMENT_NUM using the alias name CertifiedDocumentNum1.
     * @param value value to set the CERTIFIED_DOCUMENT_NUM
     */
    public void setCertifiedDocumentNum1(String value) {
        setAttributeInternal(CERTIFIEDDOCUMENTNUM1, value);
    }

    /**
     * Gets the attribute value for CERTIFIED_DOCUMENT_DATE using the alias name CertifiedocumentDate1.
     * @return the CERTIFIED_DOCUMENT_DATE
     */
    public Date getCertifiedocumentDate1() {
        return (Date)getAttributeInternal(CERTIFIEDOCUMENTDATE1);
    }

    /**
     * Sets <code>value</code> as attribute value for CERTIFIED_DOCUMENT_DATE using the alias name CertifiedocumentDate1.
     * @param value value to set the CERTIFIED_DOCUMENT_DATE
     */
    public void setCertifiedocumentDate1(Date value) {
        setAttributeInternal(CERTIFIEDOCUMENTDATE1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransProjectName.
     * @return the TransProjectName
     */
    public String getTransProjectName() {
        return (String)getAttributeInternal(TRANSPROJECTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransProjectName.
     * @param value value to set the  TransProjectName
     */
    public void setTransProjectName(String value) {
        setAttributeInternal(TRANSPROJECTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransSearchPrjStart.
     * @return the TransSearchPrjStart
     */
    public Date getTransSearchPrjStart() {
        return (Date)getAttributeInternal(TRANSSEARCHPRJSTART);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransSearchPrjStart.
     * @param value value to set the  TransSearchPrjStart
     */
    public void setTransSearchPrjStart(Date value) {
        setAttributeInternal(TRANSSEARCHPRJSTART, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransSearchPrjEnd.
     * @return the TransSearchPrjEnd
     */
    public Date getTransSearchPrjEnd() {
        return (Date)getAttributeInternal(TRANSSEARCHPRJEND);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransSearchPrjEnd.
     * @param value value to set the  TransSearchPrjEnd
     */
    public void setTransSearchPrjEnd(Date value) {
        setAttributeInternal(TRANSSEARCHPRJEND, value);
    }

    /**
     * Gets the attribute value for VERSION using the alias name Version.
     * @return the VERSION
     */
    public BigDecimal getVersion() {
        return (BigDecimal)getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION using the alias name Version.
     * @param value value to set the VERSION
     */
    public void setVersion(BigDecimal value) {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the attribute value for CERTIFIED_APPROVED_BY using the alias name CertifiedApprovedBy.
     * @return the CERTIFIED_APPROVED_BY
     */
    public String getCertifiedApprovedBy() {
        return (String)getAttributeInternal(CERTIFIEDAPPROVEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CERTIFIED_APPROVED_BY using the alias name CertifiedApprovedBy.
     * @param value value to set the CERTIFIED_APPROVED_BY
     */
    public void setCertifiedApprovedBy(String value) {
        setAttributeInternal(CERTIFIEDAPPROVEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransStatus.
     * @return the TransStatus
     */
    public String getTransStatus() {
        try {
            BillingDetailsAMImpl applicationModule =
                (BillingDetailsAMImpl)this.getApplicationModule();
            CommonUtilsAMImpl commAM =
                (CommonUtilsAMImpl)applicationModule.getCommonUtilsAM1();
            return commAM.getStatusFromCode(getCertifiedStatus());
        } catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
        }
        return null;
    }


    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransStatus.
     * @param value value to set the  TransStatus
     */
    public void setTransStatus(String value) {
        setAttributeInternal(TRANSSTATUS, value);
    }

    /**
     * Gets the attribute value for INVOICE_HEADER_ID using the alias name InvoiceHeaderId.
     * @return the INVOICE_HEADER_ID
     */
    public BigDecimal getInvoiceHeaderId() {
        return (BigDecimal)getAttributeInternal(INVOICEHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_HEADER_ID using the alias name InvoiceHeaderId.
     * @param value value to set the INVOICE_HEADER_ID
     */
    public void setInvoiceHeaderId(BigDecimal value) {
        setAttributeInternal(INVOICEHEADERID, value);
    }

    /**
     * Gets the attribute value for MASTER_BOQ_HEADER_ID using the alias name MasterBoqHeaderId.
     * @return the MASTER_BOQ_HEADER_ID
     */
    public BigDecimal getMasterBoqHeaderId() {
        return (BigDecimal)getAttributeInternal(MASTERBOQHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for MASTER_BOQ_HEADER_ID using the alias name MasterBoqHeaderId.
     * @param value value to set the MASTER_BOQ_HEADER_ID
     */
    public void setMasterBoqHeaderId(BigDecimal value) {
        setAttributeInternal(MASTERBOQHEADERID, value);
    }

    /**
     * Gets the attribute value for MASTER_CERT_HEADER_ID using the alias name MasterCertHeaderId.
     * @return the MASTER_CERT_HEADER_ID
     */
    public BigDecimal getMasterCertHeaderId() {
        return (BigDecimal)getAttributeInternal(MASTERCERTHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for MASTER_CERT_HEADER_ID using the alias name MasterCertHeaderId.
     * @param value value to set the MASTER_CERT_HEADER_ID
     */
    public void setMasterCertHeaderId(BigDecimal value) {
        setAttributeInternal(MASTERCERTHEADERID, value);
    }

    /**
     * Gets the attribute value for MASTER_INVOICE_HEADER_ID using the alias name MasterInvoiceHeaderId.
     * @return the MASTER_INVOICE_HEADER_ID
     */
    public BigDecimal getMasterInvoiceHeaderId() {
        return (BigDecimal)getAttributeInternal(MASTERINVOICEHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for MASTER_INVOICE_HEADER_ID using the alias name MasterInvoiceHeaderId.
     * @param value value to set the MASTER_INVOICE_HEADER_ID
     */
    public void setMasterInvoiceHeaderId(BigDecimal value) {
        setAttributeInternal(MASTERINVOICEHEADERID, value);
    }

    /**
     * Gets the attribute value for PARENT_CERT_HEADER_ID using the alias name ParentCertHeaderId.
     * @return the PARENT_CERT_HEADER_ID
     */
    public BigDecimal getParentCertHeaderId() {
        return (BigDecimal)getAttributeInternal(PARENTCERTHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for PARENT_CERT_HEADER_ID using the alias name ParentCertHeaderId.
     * @param value value to set the PARENT_CERT_HEADER_ID
     */
    public void setParentCertHeaderId(BigDecimal value) {
        setAttributeInternal(PARENTCERTHEADERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransStartDate.
     * @return the TransStartDate
     */
    public Date getTransStartDate() {

        try {
            RowSet rowSetItr = getMaxProjectCertifiedDocDateScrVO1();
            rowSetItr.setNamedWhereClauseParam("p_bu_id", getBusinessUnitId());
            rowSetItr.setNamedWhereClauseParam("p_prj_id", getProjectId());
            rowSetItr.executeQuery();
            if (rowSetItr.first() != null) {
                MaxProjectCertifiedDocDateScrVORowImpl row =
                    (MaxProjectCertifiedDocDateScrVORowImpl)rowSetItr.first();
                if (row.getMaxDate() != null) {
                    return row.getMaxDate();
                } else {
                    return getTransPrjStartDate();
                }
            }
        } catch (Exception e) {

        }

        return (Date)getAttributeInternal(TRANSSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransStartDate.
     * @param value value to set the  TransStartDate
     */
    public void setTransStartDate(Date value) {
        setAttributeInternal(TRANSSTARTDATE, value);
    }

    /**
     * Gets the attribute value for BOQ_HEADER_ID using the alias name BoqHeaderId.
     * @return the BOQ_HEADER_ID
     */
    public BigDecimal getBoqHeaderId() {
        return (BigDecimal)getAttributeInternal(BOQHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for BOQ_HEADER_ID using the alias name BoqHeaderId.
     * @param value value to set the BOQ_HEADER_ID
     */
    public void setBoqHeaderId(BigDecimal value) {
        setAttributeInternal(BOQHEADERID, value);
    }

    /**
     * Gets the attribute value for MASTER_CERT_HEADER_ID using the alias name MasterCertHeaderId1.
     * @return the MASTER_CERT_HEADER_ID
     */
    public BigDecimal getMasterCertHeaderId1() {
        return (BigDecimal)getAttributeInternal(MASTERCERTHEADERID1);
    }

    /**
     * Sets <code>value</code> as attribute value for MASTER_CERT_HEADER_ID using the alias name MasterCertHeaderId1.
     * @param value value to set the MASTER_CERT_HEADER_ID
     */
    public void setMasterCertHeaderId1(BigDecimal value) {
        setAttributeInternal(MASTERCERTHEADERID1, value);
    }

    /**
     * Gets the attribute value for MASTER_INVOICE_HEADER_ID using the alias name MasterInvoiceHeaderId1.
     * @return the MASTER_INVOICE_HEADER_ID
     */
    public BigDecimal getMasterInvoiceHeaderId1() {
        return (BigDecimal)getAttributeInternal(MASTERINVOICEHEADERID1);
    }

    /**
     * Sets <code>value</code> as attribute value for MASTER_INVOICE_HEADER_ID using the alias name MasterInvoiceHeaderId1.
     * @param value value to set the MASTER_INVOICE_HEADER_ID
     */
    public void setMasterInvoiceHeaderId1(BigDecimal value) {
        setAttributeInternal(MASTERINVOICEHEADERID1, value);
    }

    /**
     * Gets the attribute value for PARENT_CERT_HEADER_ID using the alias name ParentCertHeaderId1.
     * @return the PARENT_CERT_HEADER_ID
     */
    public BigDecimal getParentCertHeaderId1() {
        return (BigDecimal)getAttributeInternal(PARENTCERTHEADERID1);
    }

    /**
     * Sets <code>value</code> as attribute value for PARENT_CERT_HEADER_ID using the alias name ParentCertHeaderId1.
     * @param value value to set the PARENT_CERT_HEADER_ID
     */
    public void setParentCertHeaderId1(BigDecimal value) {
        setAttributeInternal(PARENTCERTHEADERID1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransCurrentCumltTotal.
     * @return the TransCurrentCumltTotal
     */
    public BigDecimal getTransCurrentCumltTotal() {
        if(getTransCumltTotal()!=null && getTransPreviousTotal()!=null){
            return new BigDecimal(getTransCumltTotal().doubleValue() -
                                  getTransPreviousTotal().doubleValue());
        }
        return (BigDecimal)getAttributeInternal(TRANSCURRENTCUMLTTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCurrentCumltTotal.
     * @param value value to set the  TransCurrentCumltTotal
     */
    public void setTransCurrentCumltTotal(BigDecimal value) {
        setAttributeInternal(TRANSCURRENTCUMLTTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransCumltTotal.
     * @return the TransCumltTotal
     */
    public BigDecimal getTransCumltTotal() {
//        if(getTransPreviousTotal()!=null && getTransCurrentCumltTotal()!=null){
//            return new BigDecimal(getTransPreviousTotal().doubleValue() +getTransCurrentCumltTotal().doubleValue());
//        }
        
        return (BigDecimal)getAttributeInternal(TRANSCUMLTTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCumltTotal.
     * @param value value to set the  TransCumltTotal
     */
    public void setTransCumltTotal(BigDecimal value) {
        setAttributeInternal(TRANSCUMLTTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransActualAmnt.
     * @return the TransActualAmnt
     */
    public BigDecimal getTransActualAmnt() {
        return (BigDecimal)getAttributeInternal(TRANSACTUALAMNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransActualAmnt.
     * @param value value to set the  TransActualAmnt
     */
    public void setTransActualAmnt(BigDecimal value) {
        setAttributeInternal(TRANSACTUALAMNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransInvoiceNumber.
     * @return the TransInvoiceNumber
     */
    public String getTransInvoiceNumber() {
        return (String)getAttributeInternal(TRANSINVOICENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransInvoiceNumber.
     * @param value value to set the  TransInvoiceNumber
     */
    public void setTransInvoiceNumber(String value) {
        setAttributeInternal(TRANSINVOICENUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransInvoiceVersion.
     * @return the TransInvoiceVersion
     */
    public BigDecimal getTransInvoiceVersion() {
        return (BigDecimal)getAttributeInternal(TRANSINVOICEVERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransInvoiceVersion.
     * @param value value to set the  TransInvoiceVersion
     */
    public void setTransInvoiceVersion(BigDecimal value) {
        setAttributeInternal(TRANSINVOICEVERSION, value);
    }

    /**
     * Gets the attribute value for CURRENT_FLAG using the alias name CurrentFlag.
     * @return the CURRENT_FLAG
     */
    public String getCurrentFlag() {
        return (String) getAttributeInternal(CURRENTFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENT_FLAG using the alias name CurrentFlag.
     * @param value value to set the CURRENT_FLAG
     */
    public void setCurrentFlag(String value) {
        setAttributeInternal(CURRENTFLAG, value);
    }

    /**
     * Gets the attribute value for BU_NAME using the alias name BuName1.
     * @return the BU_NAME
     */
    public String getBuName1() {
        return (String) getAttributeInternal(BUNAME1);
    }

    /**
     * Sets <code>value</code> as attribute value for BU_NAME using the alias name BuName1.
     * @param value value to set the BU_NAME
     */
    public void setBuName1(String value) {
        setAttributeInternal(BUNAME1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransPrecision.
     * @return the TransPrecision
     */
    public BigDecimal getTransPrecision() {
        return (BigDecimal) getAttributeInternal(TRANSPRECISION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransPrecision.
     * @param value value to set the  TransPrecision
     */
    public void setTransPrecision(BigDecimal value) {
        setAttributeInternal(TRANSPRECISION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransPreviousTotal.
     * @return the TransPreviousTotal
     */
    public BigDecimal getTransPreviousTotal() {
        return (BigDecimal) getAttributeInternal(TRANSPREVIOUSTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransPreviousTotal.
     * @param value value to set the  TransPreviousTotal
     */
    public void setTransPreviousTotal(BigDecimal value) {
        setAttributeInternal(TRANSPREVIOUSTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransBOQVersion.
     * @return the TransBOQVersion
     */
    public BigDecimal getTransBOQVersion() {
        return (BigDecimal) getAttributeInternal(TRANSBOQVERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransBOQVersion.
     * @param value value to set the  TransBOQVersion
     */
    public void setTransBOQVersion(BigDecimal value) {
        setAttributeInternal(TRANSBOQVERSION, value);
    }

    /**
     * Gets the attribute value for CONTRACT_ID using the alias name ContractId.
     * @return the CONTRACT_ID
     */
    public BigDecimal getContractId() {
        return (BigDecimal) getAttributeInternal(CONTRACTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_ID using the alias name ContractId.
     * @param value value to set the CONTRACT_ID
     */
    public void setContractId(BigDecimal value) {
        setAttributeInternal(CONTRACTID, value);
    }

    /**
     * Gets the attribute value for CONTRACT_NUMBER using the alias name ContractNumber.
     * @return the CONTRACT_NUMBER
     */
    public String getContractNumber() {
        return (String) getAttributeInternal(CONTRACTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_NUMBER using the alias name ContractNumber.
     * @param value value to set the CONTRACT_NUMBER
     */
    public void setContractNumber(String value) {
        setAttributeInternal(CONTRACTNUMBER, value);
    }

    /**
     * Gets the attribute value for CONTRACT_ID using the alias name ContractId1.
     * @return the CONTRACT_ID
     */
    public BigDecimal getContractId1() {
        return (BigDecimal) getAttributeInternal(CONTRACTID1);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_ID using the alias name ContractId1.
     * @param value value to set the CONTRACT_ID
     */
    public void setContractId1(BigDecimal value) {
        setAttributeInternal(CONTRACTID1, value);
    }

    /**
     * Gets the attribute value for VALUATION_DATE using the alias name ValuationDate.
     * @return the VALUATION_DATE
     */
    public Date getValuationDate() {
        return (Date) getAttributeInternal(VALUATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for VALUATION_DATE using the alias name ValuationDate.
     * @param value value to set the VALUATION_DATE
     */
    public void setValuationDate(Date value) {
        setAttributeInternal(VALUATIONDATE, value);
    }

    /**
     * Gets the attribute value for COGNOMEN using the alias name Cognomen.
     * @return the COGNOMEN
     */
    public String getCognomen() {
        return (String) getAttributeInternal(COGNOMEN);
    }

    /**
     * Sets <code>value</code> as attribute value for COGNOMEN using the alias name Cognomen.
     * @param value value to set the COGNOMEN
     */
    public void setCognomen(String value) {
        setAttributeInternal(COGNOMEN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransCustomerName.
     * @return the TransCustomerName
     */
    public String getTransCustomerName() {
        return (String) getAttributeInternal(TRANSCUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCustomerName.
     * @param value value to set the  TransCustomerName
     */
    public void setTransCustomerName(String value) {
        setAttributeInternal(TRANSCUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransCurrentFlag.
     * @return the TransCurrentFlag
     */
    public String getTransCurrentFlag() {
        return (String) getAttributeInternal(TRANSCURRENTFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCurrentFlag.
     * @param value value to set the  TransCurrentFlag
     */
    public void setTransCurrentFlag(String value) {
        setAttributeInternal(TRANSCURRENTFLAG, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UserBusinessUnitsVO1.
     */
    public RowSet getUserBusinessUnitsVO1() {
        return (RowSet)getAttributeInternal(USERBUSINESSUNITSVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PrjProjectsVO1.
     */
    public RowSet getPrjProjectsVO1() {
        return (RowSet)getAttributeInternal(PRJPROJECTSVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AgreementMonthsVO1.
     */
    public RowSet getAgreementMonthsVO1() {
        return (RowSet)getAttributeInternal(AGREEMENTMONTHSVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CertifiedQtyDetailsVO1.
     */
    public RowSet getCertifiedQtyDetailsVO1() {
        return (RowSet)getAttributeInternal(CERTIFIEDQTYDETAILSVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PrjProjectsVO2.
     */
    public RowSet getPrjProjectsVO2() {
        return (RowSet)getAttributeInternal(PRJPROJECTSVO2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AgreementMonthsVO2.
     */
    public RowSet getAgreementMonthsVO2() {
        return (RowSet)getAttributeInternal(AGREEMENTMONTHSVO2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UserBusinessUnitsVO2.
     */
    public RowSet getUserBusinessUnitsVO2() {
        return (RowSet)getAttributeInternal(USERBUSINESSUNITSVO2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MaxProjectCertifiedDocDateScrVO1.
     */
    public RowSet getMaxProjectCertifiedDocDateScrVO1() {
        return (RowSet)getAttributeInternal(MAXPROJECTCERTIFIEDDOCDATESCRVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProjectCustomerLOVVO1.
     */
    public RowSet getProjectCustomerLOVVO1() {
        return (RowSet)getAttributeInternal(PROJECTCUSTOMERLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProjectSearchVO1.
     */
    public RowSet getProjectSearchVO1() {
        return (RowSet)getAttributeInternal(PROJECTSEARCHVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CertifiedVersionLOVVO1.
     */
    public RowSet getCertifiedVersionLOVVO1() {
        return (RowSet)getAttributeInternal(CERTIFIEDVERSIONLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StaticYesorNoVO1.
     */
    public RowSet getStaticYesorNoVO1() {
        return (RowSet)getAttributeInternal(STATICYESORNOVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupVO1.
     */
    public RowSet getLookupVO1() {
        return (RowSet)getAttributeInternal(LOOKUPVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ContractHeadersVO1.
     */
    public RowSet getContractHeadersVO1() {
        return (RowSet)getAttributeInternal(CONTRACTHEADERSVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ContractHeadersVO2.
     */
    public RowSet getContractHeadersVO2() {
        return (RowSet)getAttributeInternal(CONTRACTHEADERSVO2);
    }

    public String getStatusFromCode(String code) {
        String status = null;
        if (code != null) {
            if ("D".equals(code)) {
                status = "Draft";
            } else if ("I".equals(code)) {
                status = "Pending Approval";
            } else if ("A".equals(code)) {
                status = "Approved";
            } else if ("R".equals(code)) {
                status = "Rejected";
            } else if ("S".equals(code)) {
                status = "Submitted";
            } else if ("CL".equals(code)) {
                status = "Cancelled";
            } else if ("P".equals(code)) {
                status = "Posted";
            } else if ("RV".equals(code)) {
                status = "Reversed";
            } else if ("L".equals(code)) {
                status = "Loaded";

            } else if ("E".equals(code)) {
                status = "Expo?rted";

            }
        }

        return status;
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
