package model.searchview;

import java.math.BigDecimal;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 15 11:43:57 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CertifiedLinesPopulateVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        HeaderId {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getHeaderId();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setHeaderId((BigDecimal)value);
            }
        }
        ,
        LineId {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getLineId();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setLineId((BigDecimal)value);
            }
        }
        ,
        MasterInvoiceLineId {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getMasterInvoiceLineId();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setMasterInvoiceLineId((BigDecimal)value);
            }
        }
        ,
        BoqHeaderId {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getBoqHeaderId();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setBoqHeaderId((BigDecimal)value);
            }
        }
        ,
        BoqLineId {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getBoqLineId();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setBoqLineId((BigDecimal)value);
            }
        }
        ,
        MasterBoqLineId {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getMasterBoqLineId();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setMasterBoqLineId((BigDecimal)value);
            }
        }
        ,
        BoqLevel {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getBoqLevel();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setBoqLevel((String)value);
            }
        }
        ,
        PageItem {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getPageItem();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setPageItem((String)value);
            }
        }
        ,
        Item {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getItem();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setItem((String)value);
            }
        }
        ,
        Description {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getDescription();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        BillQty {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getBillQty();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setBillQty((BigDecimal)value);
            }
        }
        ,
        FinalQty {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getFinalQty();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setFinalQty((BigDecimal)value);
            }
        }
        ,
        Uom {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getUom();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setUom((String)value);
            }
        }
        ,
        BaseLineBoqLineId {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getBaseLineBoqLineId();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setBaseLineBoqLineId((BigDecimal)value);
            }
        }
        ,
        PriceCode {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getPriceCode();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setPriceCode((String)value);
            }
        }
        ,
        LineType {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getLineType();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setLineType((String)value);
            }
        }
        ,
        WdCummulativeQty {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getWdCummulativeQty();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setWdCummulativeQty((BigDecimal)value);
            }
        }
        ,
        CurrentRate {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getCurrentRate();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setCurrentRate((BigDecimal)value);
            }
        }
        ,
        InvoiceCummulativeQty {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getInvoiceCummulativeQty();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setInvoiceCummulativeQty((BigDecimal)value);
            }
        }
        ,
        CertifiedQty {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getCertifiedQty();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setCertifiedQty((BigDecimal)value);
            }
        }
        ,
        PrevCummulativeQty {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getPrevCummulativeQty();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setPrevCummulativeQty((BigDecimal)value);
            }
        }
        ,
        PreviousRate {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getPreviousRate();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setPreviousRate((BigDecimal)value);
            }
        }
        ,
        PrevActualCertQty {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getPrevActualCertQty();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setPrevActualCertQty((BigDecimal)value);
            }
        }
        ,
        MasterCertLineId {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getMasterCertLineId();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setMasterCertLineId((BigDecimal)value);
            }
        }
        ,
        ExtendedFlag {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getExtendedFlag();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setExtendedFlag((String)value);
            }
        }
        ,
        InvCummQtyPer {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getInvCummQtyPer();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setInvCummQtyPer((BigDecimal)value);
            }
        }
        ,
        BillPageItem {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getBillPageItem();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setBillPageItem((String)value);
            }
        }
        ,
        SellingAmount {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getSellingAmount();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setSellingAmount((BigDecimal)value);
            }
        }
        ,
        TransFlag {
            public Object get(CertifiedLinesPopulateVORowImpl obj) {
                return obj.getTransFlag();
            }

            public void put(CertifiedLinesPopulateVORowImpl obj,
                            Object value) {
                obj.setTransFlag((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(CertifiedLinesPopulateVORowImpl object);

        public abstract void put(CertifiedLinesPopulateVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int MASTERINVOICELINEID = AttributesEnum.MasterInvoiceLineId.index();
    public static final int BOQHEADERID = AttributesEnum.BoqHeaderId.index();
    public static final int BOQLINEID = AttributesEnum.BoqLineId.index();
    public static final int MASTERBOQLINEID = AttributesEnum.MasterBoqLineId.index();
    public static final int BOQLEVEL = AttributesEnum.BoqLevel.index();
    public static final int PAGEITEM = AttributesEnum.PageItem.index();
    public static final int ITEM = AttributesEnum.Item.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int BILLQTY = AttributesEnum.BillQty.index();
    public static final int FINALQTY = AttributesEnum.FinalQty.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int BASELINEBOQLINEID = AttributesEnum.BaseLineBoqLineId.index();
    public static final int PRICECODE = AttributesEnum.PriceCode.index();
    public static final int LINETYPE = AttributesEnum.LineType.index();
    public static final int WDCUMMULATIVEQTY = AttributesEnum.WdCummulativeQty.index();
    public static final int CURRENTRATE = AttributesEnum.CurrentRate.index();
    public static final int INVOICECUMMULATIVEQTY = AttributesEnum.InvoiceCummulativeQty.index();
    public static final int CERTIFIEDQTY = AttributesEnum.CertifiedQty.index();
    public static final int PREVCUMMULATIVEQTY = AttributesEnum.PrevCummulativeQty.index();
    public static final int PREVIOUSRATE = AttributesEnum.PreviousRate.index();
    public static final int PREVACTUALCERTQTY = AttributesEnum.PrevActualCertQty.index();
    public static final int MASTERCERTLINEID = AttributesEnum.MasterCertLineId.index();
    public static final int EXTENDEDFLAG = AttributesEnum.ExtendedFlag.index();
    public static final int INVCUMMQTYPER = AttributesEnum.InvCummQtyPer.index();
    public static final int BILLPAGEITEM = AttributesEnum.BillPageItem.index();
    public static final int SELLINGAMOUNT = AttributesEnum.SellingAmount.index();
    public static final int TRANSFLAG = AttributesEnum.TransFlag.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CertifiedLinesPopulateVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute HeaderId.
     * @return the HeaderId
     */
    public BigDecimal getHeaderId() {
        return (BigDecimal)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HeaderId.
     * @param value value to set the  HeaderId
     */
    public void setHeaderId(BigDecimal value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LineId.
     * @return the LineId
     */
    public BigDecimal getLineId() {
        return (BigDecimal)getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LineId.
     * @param value value to set the  LineId
     */
    public void setLineId(BigDecimal value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MasterInvoiceLineId.
     * @return the MasterInvoiceLineId
     */
    public BigDecimal getMasterInvoiceLineId() {
        return (BigDecimal)getAttributeInternal(MASTERINVOICELINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MasterInvoiceLineId.
     * @param value value to set the  MasterInvoiceLineId
     */
    public void setMasterInvoiceLineId(BigDecimal value) {
        setAttributeInternal(MASTERINVOICELINEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BoqHeaderId.
     * @return the BoqHeaderId
     */
    public BigDecimal getBoqHeaderId() {
        return (BigDecimal)getAttributeInternal(BOQHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BoqHeaderId.
     * @param value value to set the  BoqHeaderId
     */
    public void setBoqHeaderId(BigDecimal value) {
        setAttributeInternal(BOQHEADERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BoqLineId.
     * @return the BoqLineId
     */
    public BigDecimal getBoqLineId() {
        return (BigDecimal)getAttributeInternal(BOQLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BoqLineId.
     * @param value value to set the  BoqLineId
     */
    public void setBoqLineId(BigDecimal value) {
        setAttributeInternal(BOQLINEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MasterBoqLineId.
     * @return the MasterBoqLineId
     */
    public BigDecimal getMasterBoqLineId() {
        return (BigDecimal)getAttributeInternal(MASTERBOQLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MasterBoqLineId.
     * @param value value to set the  MasterBoqLineId
     */
    public void setMasterBoqLineId(BigDecimal value) {
        setAttributeInternal(MASTERBOQLINEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BoqLevel.
     * @return the BoqLevel
     */
    public String getBoqLevel() {
        return (String)getAttributeInternal(BOQLEVEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BoqLevel.
     * @param value value to set the  BoqLevel
     */
    public void setBoqLevel(String value) {
        setAttributeInternal(BOQLEVEL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PageItem.
     * @return the PageItem
     */
    public String getPageItem() {
        return (String)getAttributeInternal(PAGEITEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PageItem.
     * @param value value to set the  PageItem
     */
    public void setPageItem(String value) {
        setAttributeInternal(PAGEITEM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Item.
     * @return the Item
     */
    public String getItem() {
        return (String)getAttributeInternal(ITEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Item.
     * @param value value to set the  Item
     */
    public void setItem(String value) {
        setAttributeInternal(ITEM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Description.
     * @param value value to set the  Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BillQty.
     * @return the BillQty
     */
    public BigDecimal getBillQty() {
        return (BigDecimal)getAttributeInternal(BILLQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BillQty.
     * @param value value to set the  BillQty
     */
    public void setBillQty(BigDecimal value) {
        setAttributeInternal(BILLQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FinalQty.
     * @return the FinalQty
     */
    public BigDecimal getFinalQty() {
        return (BigDecimal)getAttributeInternal(FINALQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FinalQty.
     * @param value value to set the  FinalQty
     */
    public void setFinalQty(BigDecimal value) {
        setAttributeInternal(FINALQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Uom.
     * @return the Uom
     */
    public String getUom() {
        return (String)getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Uom.
     * @param value value to set the  Uom
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BaseLineBoqLineId.
     * @return the BaseLineBoqLineId
     */
    public BigDecimal getBaseLineBoqLineId() {
        return (BigDecimal)getAttributeInternal(BASELINEBOQLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BaseLineBoqLineId.
     * @param value value to set the  BaseLineBoqLineId
     */
    public void setBaseLineBoqLineId(BigDecimal value) {
        setAttributeInternal(BASELINEBOQLINEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PriceCode.
     * @return the PriceCode
     */
    public String getPriceCode() {
        return (String)getAttributeInternal(PRICECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PriceCode.
     * @param value value to set the  PriceCode
     */
    public void setPriceCode(String value) {
        setAttributeInternal(PRICECODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LineType.
     * @return the LineType
     */
    public String getLineType() {
        return (String)getAttributeInternal(LINETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LineType.
     * @param value value to set the  LineType
     */
    public void setLineType(String value) {
        setAttributeInternal(LINETYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WdCummulativeQty.
     * @return the WdCummulativeQty
     */
    public BigDecimal getWdCummulativeQty() {
        return (BigDecimal)getAttributeInternal(WDCUMMULATIVEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WdCummulativeQty.
     * @param value value to set the  WdCummulativeQty
     */
    public void setWdCummulativeQty(BigDecimal value) {
        setAttributeInternal(WDCUMMULATIVEQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentRate.
     * @return the CurrentRate
     */
    public BigDecimal getCurrentRate() {
        return (BigDecimal)getAttributeInternal(CURRENTRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentRate.
     * @param value value to set the  CurrentRate
     */
    public void setCurrentRate(BigDecimal value) {
        setAttributeInternal(CURRENTRATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceCummulativeQty.
     * @return the InvoiceCummulativeQty
     */
    public BigDecimal getInvoiceCummulativeQty() {
        return (BigDecimal)getAttributeInternal(INVOICECUMMULATIVEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceCummulativeQty.
     * @param value value to set the  InvoiceCummulativeQty
     */
    public void setInvoiceCummulativeQty(BigDecimal value) {
        setAttributeInternal(INVOICECUMMULATIVEQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CertifiedQty.
     * @return the CertifiedQty
     */
    public BigDecimal getCertifiedQty() {
        return (BigDecimal)getAttributeInternal(CERTIFIEDQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CertifiedQty.
     * @param value value to set the  CertifiedQty
     */
    public void setCertifiedQty(BigDecimal value) {
        setAttributeInternal(CERTIFIEDQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrevCummulativeQty.
     * @return the PrevCummulativeQty
     */
    public BigDecimal getPrevCummulativeQty() {
        return (BigDecimal)getAttributeInternal(PREVCUMMULATIVEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrevCummulativeQty.
     * @param value value to set the  PrevCummulativeQty
     */
    public void setPrevCummulativeQty(BigDecimal value) {
        setAttributeInternal(PREVCUMMULATIVEQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PreviousRate.
     * @return the PreviousRate
     */
    public BigDecimal getPreviousRate() {
        return (BigDecimal)getAttributeInternal(PREVIOUSRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PreviousRate.
     * @param value value to set the  PreviousRate
     */
    public void setPreviousRate(BigDecimal value) {
        setAttributeInternal(PREVIOUSRATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrevActualCertQty.
     * @return the PrevActualCertQty
     */
    public BigDecimal getPrevActualCertQty() {
        return (BigDecimal)getAttributeInternal(PREVACTUALCERTQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrevActualCertQty.
     * @param value value to set the  PrevActualCertQty
     */
    public void setPrevActualCertQty(BigDecimal value) {
        setAttributeInternal(PREVACTUALCERTQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MasterCertLineId.
     * @return the MasterCertLineId
     */
    public BigDecimal getMasterCertLineId() {
        return (BigDecimal)getAttributeInternal(MASTERCERTLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MasterCertLineId.
     * @param value value to set the  MasterCertLineId
     */
    public void setMasterCertLineId(BigDecimal value) {
        setAttributeInternal(MASTERCERTLINEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ExtendedFlag.
     * @return the ExtendedFlag
     */
    public String getExtendedFlag() {
        return (String)getAttributeInternal(EXTENDEDFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ExtendedFlag.
     * @param value value to set the  ExtendedFlag
     */
    public void setExtendedFlag(String value) {
        setAttributeInternal(EXTENDEDFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvCummQtyPer.
     * @return the InvCummQtyPer
     */
    public BigDecimal getInvCummQtyPer() {
        return (BigDecimal)getAttributeInternal(INVCUMMQTYPER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvCummQtyPer.
     * @param value value to set the  InvCummQtyPer
     */
    public void setInvCummQtyPer(BigDecimal value) {
        setAttributeInternal(INVCUMMQTYPER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BillPageItem.
     * @return the BillPageItem
     */
    public String getBillPageItem() {
        return (String) getAttributeInternal(BILLPAGEITEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BillPageItem.
     * @param value value to set the  BillPageItem
     */
    public void setBillPageItem(String value) {
        setAttributeInternal(BILLPAGEITEM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SellingAmount.
     * @return the SellingAmount
     */
    public BigDecimal getSellingAmount() {
        return (BigDecimal) getAttributeInternal(SELLINGAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SellingAmount.
     * @param value value to set the  SellingAmount
     */
    public void setSellingAmount(BigDecimal value) {
        setAttributeInternal(SELLINGAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransFlag.
     * @return the TransFlag
     */
    public String getTransFlag() {
        return (String)getAttributeInternal(TRANSFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransFlag.
     * @param value value to set the  TransFlag
     */
    public void setTransFlag(String value) {
        setAttributeInternal(TRANSFLAG, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
