package model.searchview;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 24 18:10:35 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExpenditureOrgVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ExpenditureOrgVOImpl() {
    }

    /**
     * Returns the bind variable value for p_bu_id.
     * @return bind variable value for p_bu_id
     */
    public BigDecimal getp_bu_id() {
        return (BigDecimal)getNamedWhereClauseParam("p_bu_id");
    }

    /**
     * Sets <code>value</code> for bind variable p_bu_id.
     * @param value value to bind as p_bu_id
     */
    public void setp_bu_id(BigDecimal value) {
        setNamedWhereClauseParam("p_bu_id", value);
    }

    /**
     * Returns the bind variable value for p_date.
     * @return bind variable value for p_date
     */
    public Date getp_date() {
        return (Date)getNamedWhereClauseParam("p_date");
    }

    /**
     * Sets <code>value</code> for bind variable p_date.
     * @param value value to bind as p_date
     */
    public void setp_date(Date value) {
        setNamedWhereClauseParam("p_date", value);
    }
}
