package model.searchview;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 04 12:30:44 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GetBoqUploadedRowScrVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ApprovedBy {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getApprovedBy();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setApprovedBy((String)value);
            }
        }
        ,
        ApprovedDate {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getApprovedDate();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setApprovedDate((Date)value);
            }
        }
        ,
        BaseLine {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getBaseLine();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setBaseLine((String)value);
            }
        }
        ,
        BudgetType {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getBudgetType();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setBudgetType((String)value);
            }
        }
        ,
        BusinessUnitId {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getBusinessUnitId();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setBusinessUnitId((BigDecimal)value);
            }
        }
        ,
        CreatedBy {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CurrentFlag {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getCurrentFlag();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setCurrentFlag((String)value);
            }
        }
        ,
        FileName {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getFileName();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setFileName((String)value);
            }
        }
        ,
        IbcNumber {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getIbcNumber();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setIbcNumber((String)value);
            }
        }
        ,
        IbcReason {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getIbcReason();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setIbcReason((String)value);
            }
        }
        ,
        ImportDate {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getImportDate();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setImportDate((Date)value);
            }
        }
        ,
        IsDocumentValid {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getIsDocumentValid();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setIsDocumentValid((String)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        MasterValidationHeaderId {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getMasterValidationHeaderId();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setMasterValidationHeaderId((BigDecimal)value);
            }
        }
        ,
        ProjectId {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getProjectId();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setProjectId((BigDecimal)value);
            }
        }
        ,
        ReasonForVariation {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getReasonForVariation();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setReasonForVariation((String)value);
            }
        }
        ,
        RevisionDate {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getRevisionDate();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setRevisionDate((Date)value);
            }
        }
        ,
        Status {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getStatus();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        TotalCandyNetFinalAmount {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getTotalCandyNetFinalAmount();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setTotalCandyNetFinalAmount((BigDecimal)value);
            }
        }
        ,
        TotalCandySellingAmount {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getTotalCandySellingAmount();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setTotalCandySellingAmount((BigDecimal)value);
            }
        }
        ,
        TotalNetFinalAmount {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getTotalNetFinalAmount();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setTotalNetFinalAmount((BigDecimal)value);
            }
        }
        ,
        ValidationHeaderId {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getValidationHeaderId();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setValidationHeaderId((BigDecimal)value);
            }
        }
        ,
        Version {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getVersion();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setVersion((BigDecimal)value);
            }
        }
        ,
        BaseLineValidationHdrId {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getBaseLineValidationHdrId();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setBaseLineValidationHdrId((BigDecimal)value);
            }
        }
        ,
        ContractId {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getContractId();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setContractId((BigDecimal)value);
            }
        }
        ,
        ContractType {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getContractType();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setContractType((String)value);
            }
        }
        ,
        Description {
            public Object get(GetBoqUploadedRowScrVORowImpl obj) {
                return obj.getDescription();
            }

            public void put(GetBoqUploadedRowScrVORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(GetBoqUploadedRowScrVORowImpl object);

        public abstract void put(GetBoqUploadedRowScrVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int APPROVEDBY = AttributesEnum.ApprovedBy.index();
    public static final int APPROVEDDATE = AttributesEnum.ApprovedDate.index();
    public static final int BASELINE = AttributesEnum.BaseLine.index();
    public static final int BUDGETTYPE = AttributesEnum.BudgetType.index();
    public static final int BUSINESSUNITID = AttributesEnum.BusinessUnitId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CURRENTFLAG = AttributesEnum.CurrentFlag.index();
    public static final int FILENAME = AttributesEnum.FileName.index();
    public static final int IBCNUMBER = AttributesEnum.IbcNumber.index();
    public static final int IBCREASON = AttributesEnum.IbcReason.index();
    public static final int IMPORTDATE = AttributesEnum.ImportDate.index();
    public static final int ISDOCUMENTVALID = AttributesEnum.IsDocumentValid.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int MASTERVALIDATIONHEADERID = AttributesEnum.MasterValidationHeaderId.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int REASONFORVARIATION = AttributesEnum.ReasonForVariation.index();
    public static final int REVISIONDATE = AttributesEnum.RevisionDate.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int TOTALCANDYNETFINALAMOUNT = AttributesEnum.TotalCandyNetFinalAmount.index();
    public static final int TOTALCANDYSELLINGAMOUNT = AttributesEnum.TotalCandySellingAmount.index();
    public static final int TOTALNETFINALAMOUNT = AttributesEnum.TotalNetFinalAmount.index();
    public static final int VALIDATIONHEADERID = AttributesEnum.ValidationHeaderId.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int BASELINEVALIDATIONHDRID = AttributesEnum.BaseLineValidationHdrId.index();
    public static final int CONTRACTID = AttributesEnum.ContractId.index();
    public static final int CONTRACTTYPE = AttributesEnum.ContractType.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GetBoqUploadedRowScrVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ValidationHeaderId.
     * @return the ValidationHeaderId
     */
    public BigDecimal getValidationHeaderId() {
        return (BigDecimal)getAttributeInternal(VALIDATIONHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ValidationHeaderId.
     * @param value value to set the  ValidationHeaderId
     */
    public void setValidationHeaderId(BigDecimal value) {
        setAttributeInternal(VALIDATIONHEADERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BusinessUnitId.
     * @return the BusinessUnitId
     */
    public BigDecimal getBusinessUnitId() {
        return (BigDecimal)getAttributeInternal(BUSINESSUNITID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BusinessUnitId.
     * @param value value to set the  BusinessUnitId
     */
    public void setBusinessUnitId(BigDecimal value) {
        setAttributeInternal(BUSINESSUNITID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProjectId.
     * @return the ProjectId
     */
    public BigDecimal getProjectId() {
        return (BigDecimal)getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProjectId.
     * @param value value to set the  ProjectId
     */
    public void setProjectId(BigDecimal value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ReasonForVariation.
     * @return the ReasonForVariation
     */
    public String getReasonForVariation() {
        return (String)getAttributeInternal(REASONFORVARIATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ReasonForVariation.
     * @param value value to set the  ReasonForVariation
     */
    public void setReasonForVariation(String value) {
        setAttributeInternal(REASONFORVARIATION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Version.
     * @return the Version
     */
    public BigDecimal getVersion() {
        return (BigDecimal)getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Version.
     * @param value value to set the  Version
     */
    public void setVersion(BigDecimal value) {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BaseLineValidationHdrId.
     * @return the BaseLineValidationHdrId
     */
    public BigDecimal getBaseLineValidationHdrId() {
        return (BigDecimal)getAttributeInternal(BASELINEVALIDATIONHDRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BaseLineValidationHdrId.
     * @param value value to set the  BaseLineValidationHdrId
     */
    public void setBaseLineValidationHdrId(BigDecimal value) {
        setAttributeInternal(BASELINEVALIDATIONHDRID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ContractId.
     * @return the ContractId
     */
    public BigDecimal getContractId() {
        return (BigDecimal)getAttributeInternal(CONTRACTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ContractId.
     * @param value value to set the  ContractId
     */
    public void setContractId(BigDecimal value) {
        setAttributeInternal(CONTRACTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ContractType.
     * @return the ContractType
     */
    public String getContractType() {
        return (String)getAttributeInternal(CONTRACTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ContractType.
     * @param value value to set the  ContractType
     */
    public void setContractType(String value) {
        setAttributeInternal(CONTRACTTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Description.
     * @param value value to set the  Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Status.
     * @return the Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Status.
     * @param value value to set the  Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BudgetType.
     * @return the BudgetType
     */
    public String getBudgetType() {
        return (String)getAttributeInternal(BUDGETTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BudgetType.
     * @param value value to set the  BudgetType
     */
    public void setBudgetType(String value) {
        setAttributeInternal(BUDGETTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IbcNumber.
     * @return the IbcNumber
     */
    public String getIbcNumber() {
        return (String)getAttributeInternal(IBCNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IbcNumber.
     * @param value value to set the  IbcNumber
     */
    public void setIbcNumber(String value) {
        setAttributeInternal(IBCNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ApprovedBy.
     * @return the ApprovedBy
     */
    public String getApprovedBy() {
        return (String)getAttributeInternal(APPROVEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ApprovedBy.
     * @param value value to set the  ApprovedBy
     */
    public void setApprovedBy(String value) {
        setAttributeInternal(APPROVEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ApprovedDate.
     * @return the ApprovedDate
     */
    public Date getApprovedDate() {
        return (Date)getAttributeInternal(APPROVEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ApprovedDate.
     * @param value value to set the  ApprovedDate
     */
    public void setApprovedDate(Date value) {
        setAttributeInternal(APPROVEDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BaseLine.
     * @return the BaseLine
     */
    public String getBaseLine() {
        return (String)getAttributeInternal(BASELINE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BaseLine.
     * @param value value to set the  BaseLine
     */
    public void setBaseLine(String value) {
        setAttributeInternal(BASELINE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreationDate.
     * @param value value to set the  CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentFlag.
     * @return the CurrentFlag
     */
    public String getCurrentFlag() {
        return (String)getAttributeInternal(CURRENTFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentFlag.
     * @param value value to set the  CurrentFlag
     */
    public void setCurrentFlag(String value) {
        setAttributeInternal(CURRENTFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FileName.
     * @return the FileName
     */
    public String getFileName() {
        return (String)getAttributeInternal(FILENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FileName.
     * @param value value to set the  FileName
     */
    public void setFileName(String value) {
        setAttributeInternal(FILENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy.
     * @param value value to set the  CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedDate.
     * @param value value to set the  LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy.
     * @param value value to set the  LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IbcReason.
     * @return the IbcReason
     */
    public String getIbcReason() {
        return (String)getAttributeInternal(IBCREASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IbcReason.
     * @param value value to set the  IbcReason
     */
    public void setIbcReason(String value) {
        setAttributeInternal(IBCREASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RevisionDate.
     * @return the RevisionDate
     */
    public Date getRevisionDate() {
        return (Date)getAttributeInternal(REVISIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RevisionDate.
     * @param value value to set the  RevisionDate
     */
    public void setRevisionDate(Date value) {
        setAttributeInternal(REVISIONDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ImportDate.
     * @return the ImportDate
     */
    public Date getImportDate() {
        return (Date)getAttributeInternal(IMPORTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ImportDate.
     * @param value value to set the  ImportDate
     */
    public void setImportDate(Date value) {
        setAttributeInternal(IMPORTDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsDocumentValid.
     * @return the IsDocumentValid
     */
    public String getIsDocumentValid() {
        return (String)getAttributeInternal(ISDOCUMENTVALID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsDocumentValid.
     * @param value value to set the  IsDocumentValid
     */
    public void setIsDocumentValid(String value) {
        setAttributeInternal(ISDOCUMENTVALID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalNetFinalAmount.
     * @return the TotalNetFinalAmount
     */
    public BigDecimal getTotalNetFinalAmount() {
        return (BigDecimal)getAttributeInternal(TOTALNETFINALAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalNetFinalAmount.
     * @param value value to set the  TotalNetFinalAmount
     */
    public void setTotalNetFinalAmount(BigDecimal value) {
        setAttributeInternal(TOTALNETFINALAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalCandyNetFinalAmount.
     * @return the TotalCandyNetFinalAmount
     */
    public BigDecimal getTotalCandyNetFinalAmount() {
        return (BigDecimal)getAttributeInternal(TOTALCANDYNETFINALAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalCandyNetFinalAmount.
     * @param value value to set the  TotalCandyNetFinalAmount
     */
    public void setTotalCandyNetFinalAmount(BigDecimal value) {
        setAttributeInternal(TOTALCANDYNETFINALAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalCandySellingAmount.
     * @return the TotalCandySellingAmount
     */
    public BigDecimal getTotalCandySellingAmount() {
        return (BigDecimal)getAttributeInternal(TOTALCANDYSELLINGAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalCandySellingAmount.
     * @param value value to set the  TotalCandySellingAmount
     */
    public void setTotalCandySellingAmount(BigDecimal value) {
        setAttributeInternal(TOTALCANDYSELLINGAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MasterValidationHeaderId.
     * @return the MasterValidationHeaderId
     */
    public BigDecimal getMasterValidationHeaderId() {
        return (BigDecimal)getAttributeInternal(MASTERVALIDATIONHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MasterValidationHeaderId.
     * @param value value to set the  MasterValidationHeaderId
     */
    public void setMasterValidationHeaderId(BigDecimal value) {
        setAttributeInternal(MASTERVALIDATIONHEADERID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
