package model.searchview;

import java.math.BigDecimal;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 05 11:23:11 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class JobTemplateRescCountVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ActivityJobId {
            public Object get(JobTemplateRescCountVORowImpl obj) {
                return obj.getActivityJobId();
            }

            public void put(JobTemplateRescCountVORowImpl obj, Object value) {
                obj.setActivityJobId((BigDecimal)value);
            }
        },
        JobResourceId {
            public Object get(JobTemplateRescCountVORowImpl obj) {
                return obj.getJobResourceId();
            }

            public void put(JobTemplateRescCountVORowImpl obj, Object value) {
                obj.setJobResourceId((BigDecimal)value);
            }
        },
        ItemId {
            public Object get(JobTemplateRescCountVORowImpl obj) {
                return obj.getItemId();
            }

            public void put(JobTemplateRescCountVORowImpl obj, Object value) {
                obj.setItemId((BigDecimal)value);
            }
        },
        Quantity {
            public Object get(JobTemplateRescCountVORowImpl obj) {
                return obj.getQuantity();
            }

            public void put(JobTemplateRescCountVORowImpl obj, Object value) {
                obj.setQuantity((BigDecimal)value);
            }
        },
        ItemRate {
            public Object get(JobTemplateRescCountVORowImpl obj) {
                return obj.getItemRate();
            }

            public void put(JobTemplateRescCountVORowImpl obj, Object value) {
                obj.setItemRate((BigDecimal)value);
            }
        },
        Amount {
            public Object get(JobTemplateRescCountVORowImpl obj) {
                return obj.getAmount();
            }

            public void put(JobTemplateRescCountVORowImpl obj, Object value) {
                obj.setAmount((BigDecimal)value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(JobTemplateRescCountVORowImpl object);

        public abstract void put(JobTemplateRescCountVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ACTIVITYJOBID =
        AttributesEnum.ActivityJobId.index();
    public static final int JOBRESOURCEID =
        AttributesEnum.JobResourceId.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int ITEMRATE = AttributesEnum.ItemRate.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();

    /**
     * This is the default constructor (do not remove).
     */
    public JobTemplateRescCountVORowImpl() {
    }


    /**
     * Gets the attribute value for the calculated attribute ActivityJobId.
     * @return the ActivityJobId
     */
    public BigDecimal getActivityJobId() {
        return (BigDecimal)getAttributeInternal(ACTIVITYJOBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ActivityJobId.
     * @param value value to set the  ActivityJobId
     */
    public void setActivityJobId(BigDecimal value) {
        setAttributeInternal(ACTIVITYJOBID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute JobResourceId.
     * @return the JobResourceId
     */
    public BigDecimal getJobResourceId() {
        return (BigDecimal)getAttributeInternal(JOBRESOURCEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute JobResourceId.
     * @param value value to set the  JobResourceId
     */
    public void setJobResourceId(BigDecimal value) {
        setAttributeInternal(JOBRESOURCEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemId.
     * @return the ItemId
     */
    public BigDecimal getItemId() {
        return (BigDecimal)getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItemId.
     * @param value value to set the  ItemId
     */
    public void setItemId(BigDecimal value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Quantity.
     * @return the Quantity
     */
    public BigDecimal getQuantity() {
        return (BigDecimal)getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Quantity.
     * @param value value to set the  Quantity
     */
    public void setQuantity(BigDecimal value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemRate.
     * @return the ItemRate
     */
    public BigDecimal getItemRate() {
        return (BigDecimal)getAttributeInternal(ITEMRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItemRate.
     * @param value value to set the  ItemRate
     */
    public void setItemRate(BigDecimal value) {
        setAttributeInternal(ITEMRATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Amount.
     * @return the Amount
     */
    public BigDecimal getAmount() {
        return (BigDecimal)getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Amount.
     * @param value value to set the  Amount
     */
    public void setAmount(BigDecimal value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
