package model.searchview;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 04 10:04:20 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MaxJobActivityTemplateResourceIdVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MaxJobActivityTemplateResourceIdVOImpl() {
    }

    /**
     * Returns the bind variable value for p_job_act_temp_id.
     * @return bind variable value for p_job_act_temp_id
     */
    public BigDecimal getp_job_act_temp_id() {
        return (BigDecimal)getNamedWhereClauseParam("p_job_act_temp_id");
    }

    /**
     * Sets <code>value</code> for bind variable p_job_act_temp_id.
     * @param value value to bind as p_job_act_temp_id
     */
    public void setp_job_act_temp_id(BigDecimal value) {
        setNamedWhereClauseParam("p_job_act_temp_id", value);
    }
}
