package model.masterview;

import java.math.BigDecimal;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 12 14:52:41 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PONumbersVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PoNumber {
            public Object get(PONumbersVORowImpl obj) {
                return obj.getPoNumber();
            }

            public void put(PONumbersVORowImpl obj, Object value) {
                obj.setPoNumber((String)value);
            }
        },
        PoHeaderId {
            public Object get(PONumbersVORowImpl obj) {
                return obj.getPoHeaderId();
            }

            public void put(PONumbersVORowImpl obj, Object value) {
                obj.setPoHeaderId((BigDecimal)value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PONumbersVORowImpl object);

        public abstract void put(PONumbersVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PONUMBER = AttributesEnum.PoNumber.index();
    public static final int POHEADERID = AttributesEnum.PoHeaderId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PONumbersVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute PoNumber.
     * @return the PoNumber
     */
    public String getPoNumber() {
        return (String)getAttributeInternal(PONUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PoNumber.
     * @param value value to set the  PoNumber
     */
    public void setPoNumber(String value) {
        setAttributeInternal(PONUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PoHeaderId.
     * @return the PoHeaderId
     */
    public BigDecimal getPoHeaderId() {
        return (BigDecimal)getAttributeInternal(POHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PoHeaderId.
     * @param value value to set the  PoHeaderId
     */
    public void setPoHeaderId(BigDecimal value) {
        setAttributeInternal(POHEADERID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
